window.REVIEW_ACTIONS = [
  {
    "actionId": "gameplay.level.select",
    "system": "主玩法",
    "sourceState": "gameplay.level_select",
    "control": "直接选择矿层卡片",
    "condition": "在选关弹窗中且目标关卡为 1–20",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "inline_state",
    "resultState": "gameplay.level_select",
    "popupTemplate": "none",
    "errorState": "gameplay.depth_locked"
  },
  {
    "actionId": "gameplay.level.previous",
    "system": "主玩法",
    "sourceState": "gameplay.level_select",
    "control": "上一关",
    "condition": "存在更浅且已解锁关卡",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "inline_state",
    "resultState": "gameplay.level_select.previous",
    "popupTemplate": "none",
    "errorState": "gameplay.level_first_toast"
  },
  {
    "actionId": "gameplay.level.next",
    "system": "主玩法",
    "sourceState": "gameplay.level_select",
    "control": "下一关",
    "condition": "目标关卡已由财富等级解锁",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "inline_state",
    "resultState": "gameplay.level_select.next",
    "popupTemplate": "none",
    "errorState": "gameplay.depth_locked"
  },
  {
    "actionId": "gameplay.level.locked",
    "system": "主玩法",
    "sourceState": "gameplay.level_select",
    "control": "未解锁关卡卡片",
    "condition": "目标深度超过财富等级上限",
    "feedbackEffect": "fx.lock.shake",
    "resultType": "popup",
    "resultState": "gameplay.depth_locked",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "gameplay.level.enter",
    "system": "主玩法",
    "sourceState": "gameplay.level_select",
    "control": "消耗本关金币进入",
    "condition": "选关弹窗打开、目标关卡为 1–20 且金币足够支付本关费用",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "transaction",
    "resultState": "gameplay.board",
    "popupTemplate": "none",
    "errorState": "gameplay.coins_insufficient"
  },
  {
    "actionId": "gameplay.tutorial.next",
    "system": "主玩法",
    "sourceState": "gameplay.tutorial_step",
    "control": "高亮目标区域",
    "condition": "首次进入第1或第2教学关且完成当前动作",
    "feedbackEffect": "fx.tutorial.pulse",
    "resultType": "inline_state",
    "resultState": "gameplay.tutorial_next_step",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "gameplay.tile.flag",
    "system": "主玩法",
    "sourceState": "gameplay.board",
    "control": "单击未开启格",
    "condition": "格子可操作",
    "feedbackEffect": "fx.tile.flag_pop",
    "resultType": "inline_state",
    "resultState": "gameplay.board.flagged",
    "popupTemplate": "none",
    "errorState": "gameplay.tile_blocked"
  },
  {
    "actionId": "gameplay.tile.dig",
    "system": "主玩法",
    "sourceState": "gameplay.board",
    "control": "双击未开启格",
    "condition": "剩余铲子≥1且格子未挖掘；旗标自动取消",
    "feedbackEffect": "fx.tile.dig_burst",
    "resultType": "inline_state",
    "resultState": "gameplay.board.dug",
    "popupTemplate": "none",
    "errorState": "gameplay.shovel_energy_empty"
  },
  {
    "actionId": "gameplay.radar.watch_ad",
    "system": "主玩法",
    "sourceState": "gameplay.board",
    "control": "雷达指南·广告",
    "condition": "本局仍有未发现宝物且广告可用",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "inline_state",
    "resultState": "gameplay.board.radar_reveal",
    "popupTemplate": "none",
    "errorState": "common.ad_unavailable"
  },
  {
    "actionId": "gameplay.energy.info",
    "system": "主玩法",
    "sourceState": "gameplay.board",
    "control": "铲子能量图标",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "gameplay.energy_rules",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "gameplay.fail.revive",
    "system": "主玩法",
    "sourceState": "gameplay.failed",
    "control": "看广告复活+2铲",
    "condition": "广告完成",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "transaction",
    "resultState": "gameplay.board.revive_plus2",
    "popupTemplate": "none",
    "errorState": "common.ad_unavailable"
  },
  {
    "actionId": "gameplay.fail.restart",
    "system": "主玩法",
    "sourceState": "gameplay.failed",
    "control": "消耗本关金币重开",
    "condition": "挖矿失败弹窗打开、铲子耗尽且未通关，目标关卡已开放且金币足够",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "transaction",
    "resultState": "gameplay.board.restarted",
    "popupTemplate": "none",
    "errorState": "gameplay.coins_insufficient"
  },
  {
    "actionId": "gameplay.success.collect",
    "system": "主玩法",
    "sourceState": "gameplay.success",
    "control": "领取全部",
    "condition": "奖励尚未领取",
    "feedbackEffect": "fx.reward.burst",
    "resultType": "transaction",
    "resultState": "gameplay.reward_received",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "gameplay.reward_claimed"
  },
  {
    "actionId": "gameplay.reward.dismiss",
    "system": "主玩法",
    "sourceState": "gameplay.reward_received",
    "control": "弹窗遮罩或系统返回",
    "condition": "奖励已写入仓库",
    "feedbackEffect": "fx.popup.fade_out",
    "resultType": "navigation",
    "resultState": "main.home",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "none"
  },
  {
    "actionId": "home.play",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "开始挖矿",
    "condition": "主界面且无其他弹窗，不扣资源、不判断体力",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "popup",
    "resultState": "gameplay.level_select",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "home.profile.open",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "头像昵称卡",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "home.profile_detail",
    "popupTemplate": "common.sheet.profile",
    "errorState": "none"
  },
  {
    "actionId": "profile.avatar.open",
    "system": "角色档案",
    "sourceState": "home.profile_detail",
    "control": "头像",
    "condition": "已打开角色档案",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "home.profile_avatar",
    "popupTemplate": "common.sheet.avatar_picker",
    "errorState": "none"
  },
  {
    "actionId": "profile.avatar.select",
    "system": "角色档案",
    "sourceState": "home.profile_avatar",
    "control": "美容头像选项",
    "condition": "选择有效美容头像",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "state_change",
    "resultState": "home.profile_detail",
    "popupTemplate": "common.sheet.avatar_picker",
    "errorState": "none"
  },
  {
    "actionId": "profile.nickname.edit",
    "system": "角色档案",
    "sourceState": "home.profile_detail",
    "control": "昵称编辑按钮",
    "condition": "已打开角色档案",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "home.profile_nickname",
    "popupTemplate": "common.sheet.form",
    "errorState": "none"
  },
  {
    "actionId": "profile.nickname.save",
    "system": "角色档案",
    "sourceState": "home.profile_nickname",
    "control": "保存昵称",
    "condition": "昵称为 2–12 个字",
    "feedbackEffect": "fx.save.stamp",
    "resultType": "state_change",
    "resultState": "home.profile_detail",
    "popupTemplate": "common.sheet.form",
    "errorState": "nickname.invalid"
  },
  {
    "actionId": "home.wealth.open",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "财富等级卡",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "home.wealth_detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "home.ranking.open",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "排行榜",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "ranking.wealth",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "home.warehouse.open",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "仓库",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "warehouse.catalog",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "home.debt.open",
    "system": "主界面",
    "sourceState": "main.home_debt",
    "control": "右上角欠债卡",
    "condition": "剩余债务>0",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "lending.debt",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "home.lending.open",
    "system": "主界面",
    "sourceState": "main.home_debt_cleared",
    "control": "右上角放贷卡",
    "condition": "债务清零",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "lending.hall",
    "popupTemplate": "none",
    "errorState": "lending.pass_required"
  },
  {
    "actionId": "home.loan.active",
    "system": "主界面",
    "sourceState": "main.home_loan_active",
    "control": "右上角借据倒计时卡",
    "condition": "至少一笔借据进行中",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "lending.notes",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "home.loan.matured",
    "system": "主界面",
    "sourceState": "main.home_loan_matured",
    "control": "右上角待领取卡",
    "condition": "至少一笔按时归还待领取",
    "feedbackEffect": "fx.status.green_pulse",
    "resultType": "popup",
    "resultState": "lending.note_matured",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "home.loan.runaway",
    "system": "主界面",
    "sourceState": "main.home_loan_runaway",
    "control": "右上角本金损失卡",
    "condition": "至少一笔跑路待确认",
    "feedbackEffect": "fx.status.red_pulse",
    "resultType": "popup",
    "resultState": "lending.note_runaway",
    "popupTemplate": "common.dialog.warning",
    "errorState": "none"
  },
  {
    "actionId": "home.guild.open",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "矿工协会",
    "condition": "已加入协会则进入协会；否则进入申请",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "guild.route",
    "popupTemplate": "none",
    "errorState": "guild_apply.pass_required"
  },
  {
    "actionId": "home.miner_pass",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "VIP证",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "home.miner_pass",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "home.miner_pass.renew_ad",
    "system": "主界面",
    "sourceState": "home.miner_pass_expired",
    "control": "支持鼓励下我们（广告）",
    "condition": "广告完成",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "transaction",
    "resultState": "home.miner_pass_active",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "common.ad_unavailable"
  },
  {
    "actionId": "home.locked_feature",
    "system": "主界面",
    "sourceState": "main.home",
    "control": "非本期功能锁定入口",
    "condition": "功能不在当前9系统范围",
    "feedbackEffect": "fx.lock.shake",
    "resultType": "toast",
    "resultState": "home.feature_locked",
    "popupTemplate": "common.toast",
    "errorState": "none"
  },
  {
    "actionId": "ranking.tab.wealth",
    "system": "排行榜",
    "sourceState": "ranking.depth",
    "control": "财富榜页签",
    "condition": "始终可用",
    "feedbackEffect": "fx.tab.slide",
    "resultType": "inline_state",
    "resultState": "ranking.wealth",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "ranking.tab.depth",
    "system": "排行榜",
    "sourceState": "ranking.wealth",
    "control": "深度榜页签",
    "condition": "始终可用",
    "feedbackEffect": "fx.tab.slide",
    "resultType": "inline_state",
    "resultState": "ranking.depth",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "ranking.rules.open",
    "system": "排行榜",
    "sourceState": "ranking.wealth|ranking.depth",
    "control": "规则图标",
    "condition": "始终可用",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "ranking.rules",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "ranking.back",
    "system": "排行榜",
    "sourceState": "ranking.wealth|ranking.depth",
    "control": "系统返回",
    "condition": "始终可用",
    "feedbackEffect": "fx.screen.slide_right",
    "resultType": "navigation",
    "resultState": "main.home",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "debt.amount.minus",
    "system": "放贷/还款",
    "sourceState": "lending.debt",
    "control": "减号",
    "condition": "偿还金额>最小步长",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "lending.debt_amount_changed",
    "popupTemplate": "none",
    "errorState": "debt.amount_min"
  },
  {
    "actionId": "debt.amount.plus",
    "system": "放贷/还款",
    "sourceState": "lending.debt",
    "control": "加号",
    "condition": "偿还金额<min(金币,剩余债务)",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "lending.debt_amount_changed",
    "popupTemplate": "none",
    "errorState": "debt.coin_insufficient"
  },
  {
    "actionId": "debt.amount.max",
    "system": "放贷/还款",
    "sourceState": "lending.debt",
    "control": "最大",
    "condition": "金币>0且剩余债务>0",
    "feedbackEffect": "fx.value.snap",
    "resultType": "inline_state",
    "resultState": "lending.debt_amount_max",
    "popupTemplate": "none",
    "errorState": "debt.coin_insufficient"
  },
  {
    "actionId": "debt.repay.open",
    "system": "放贷/还款",
    "sourceState": "lending.debt",
    "control": "确认还款",
    "condition": "偿还金额有效",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "popup",
    "resultState": "lending.debt_confirm",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "debt.amount_invalid"
  },
  {
    "actionId": "debt.repay.commit",
    "system": "放贷/还款",
    "sourceState": "lending.debt_confirm",
    "control": "偿还",
    "condition": "二次校验金币与剩余债务",
    "feedbackEffect": "fx.coin.fly",
    "resultType": "transaction",
    "resultState": "lending.debt_repaid",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "debt.coin_changed"
  },
  {
    "actionId": "debt.unlock.lending",
    "system": "放贷/还款",
    "sourceState": "lending.debt_repaid",
    "control": "债务清零自动状态变化",
    "condition": "剩余债务=0",
    "feedbackEffect": "fx.unlock.glow",
    "resultType": "popup",
    "resultState": "lending.unlocked",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "lending.tab.hall",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "放贷大厅页签",
    "condition": "债务清零且VIP证有效",
    "feedbackEffect": "fx.tab.slide",
    "resultType": "inline_state",
    "resultState": "lending.hall",
    "popupTemplate": "none",
    "errorState": "lending.pass_required"
  },
  {
    "actionId": "lending.tab.notes",
    "system": "放贷/还款",
    "sourceState": "lending.hall",
    "control": "我的借据页签",
    "condition": "始终可用，VIP证过期也可查看",
    "feedbackEffect": "fx.tab.slide",
    "resultType": "inline_state",
    "resultState": "lending.notes",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "lending.refresh.ad",
    "system": "放贷/还款",
    "sourceState": "lending.hall",
    "control": "广告·立即刷新",
    "condition": "VIP证有效且广告完成",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "transaction",
    "resultState": "lending.hall_refreshed",
    "popupTemplate": "none",
    "errorState": "lending.pass_or_ad_unavailable"
  },
  {
    "actionId": "lending.candidate.select",
    "system": "放贷/还款",
    "sourceState": "lending.hall",
    "control": "候选合同卡",
    "condition": "VIP证有效、候选人未放贷、借据槽位未满、金币足够",
    "feedbackEffect": "fx.card.selected",
    "resultType": "popup",
    "resultState": "lending.loan_confirm",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "lending.candidate_unavailable"
  },
  {
    "actionId": "lending.candidate.loaned",
    "system": "放贷/还款",
    "sourceState": "lending.hall",
    "control": "已放贷合同卡",
    "condition": "该候选已签约",
    "feedbackEffect": "fx.card.disabled",
    "resultType": "inline_state",
    "resultState": "lending.notes_focus_matching",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "lending.loan.commit",
    "system": "放贷/还款",
    "sourceState": "lending.loan_confirm",
    "control": "签署借据并放贷",
    "condition": "合同参数未变、VIP证有效、金币和槽位仍满足",
    "feedbackEffect": "fx.contract.stamp",
    "resultType": "transaction",
    "resultState": "lending.loan_active",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "lending.commit_failed"
  },
  {
    "actionId": "lending.pass.activate_ad",
    "system": "放贷/还款",
    "sourceState": "lending.pass_required",
    "control": "看广告激活3天",
    "condition": "广告完成",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "transaction",
    "resultState": "lending.hall",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "common.ad_unavailable"
  },
  {
    "actionId": "lending.note.active.open",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "进行中借据卡",
    "condition": "借据状态=active",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "lending.note_active_detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "lending.note.matured.open",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "到期待领取借据卡",
    "condition": "借据状态=matured",
    "feedbackEffect": "fx.status.green_pulse",
    "resultType": "popup",
    "resultState": "lending.note_matured",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "lending.note.collect",
    "system": "放贷/还款",
    "sourceState": "lending.note_matured",
    "control": "领取本息",
    "condition": "借据状态=matured且未领取",
    "feedbackEffect": "fx.reward.burst",
    "resultType": "transaction",
    "resultState": "lending.note_repaid_recorded",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "lending.note_already_settled"
  },
  {
    "actionId": "lending.note.runaway.open",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "跑路借据卡·了解",
    "condition": "借据状态=runaway",
    "feedbackEffect": "fx.status.red_pulse",
    "resultType": "popup",
    "resultState": "lending.note_runaway",
    "popupTemplate": "common.dialog.warning",
    "errorState": "none"
  },
  {
    "actionId": "lending.note.runaway.ack",
    "system": "放贷/还款",
    "sourceState": "lending.note_runaway",
    "control": "确认损失",
    "condition": "借据状态=runaway且未结算",
    "feedbackEffect": "fx.loss.fade",
    "resultType": "transaction",
    "resultState": "lending.note_runaway_recorded",
    "popupTemplate": "common.dialog.warning",
    "errorState": "lending.note_already_settled"
  },
  {
    "actionId": "lending.history.open",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "记录图标",
    "condition": "存在已完成借据",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "lending.history",
    "popupTemplate": "common.sheet.info",
    "errorState": "lending.history_empty"
  },
  {
    "actionId": "lending.history.item",
    "system": "放贷/还款",
    "sourceState": "lending.history",
    "control": "历史借据条目",
    "condition": "始终可用",
    "feedbackEffect": "fx.row.highlight",
    "resultType": "inline_state",
    "resultState": "lending.history_detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "lending.slot.empty",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "空闲借据槽位",
    "condition": "VIP证有效",
    "feedbackEffect": "fx.card.highlight",
    "resultType": "inline_state",
    "resultState": "lending.hall",
    "popupTemplate": "none",
    "errorState": "lending.pass_required"
  },
  {
    "actionId": "lending.slot.locked",
    "system": "放贷/还款",
    "sourceState": "lending.notes",
    "control": "未解锁借据槽位",
    "condition": "财富等级未达到该槽位要求",
    "feedbackEffect": "fx.lock.shake",
    "resultType": "popup",
    "resultState": "lending.slot_unlock_requirement",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "guild.members.open",
    "system": "工会",
    "sourceState": "guild.home",
    "control": "成员名单",
    "condition": "已加入协会",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "guild.members",
    "popupTemplate": "none",
    "errorState": "guild.not_joined"
  },
  {
    "actionId": "guild.member.open",
    "system": "工会",
    "sourceState": "guild.members",
    "control": "成员行",
    "condition": "始终可用",
    "feedbackEffect": "fx.row.highlight",
    "resultType": "popup",
    "resultState": "guild.member_detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "guild.manage.open",
    "system": "工会",
    "sourceState": "guild.home",
    "control": "会长管理小图标",
    "condition": "当前玩家=会长",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "navigation",
    "resultState": "guild.manage",
    "popupTemplate": "none",
    "errorState": "guild.permission_denied"
  },
  {
    "actionId": "guild.member.kick.open",
    "system": "工会",
    "sourceState": "guild.member_detail",
    "control": "移出协会",
    "condition": "会长且目标不是自己",
    "feedbackEffect": "fx.press.red_flash",
    "resultType": "popup",
    "resultState": "guild.member_kick_confirm",
    "popupTemplate": "common.dialog.warning",
    "errorState": "guild.permission_or_target_invalid"
  },
  {
    "actionId": "guild.member.kick.commit",
    "system": "工会",
    "sourceState": "guild.member_kick_confirm",
    "control": "移出成员",
    "condition": "二次校验会长权限与成员存在",
    "feedbackEffect": "fx.member.remove",
    "resultType": "transaction",
    "resultState": "guild.member_removed",
    "popupTemplate": "common.dialog.warning",
    "errorState": "guild.member_changed"
  },
  {
    "actionId": "guild.member.role.open",
    "system": "工会",
    "sourceState": "guild.member_detail",
    "control": "调整职务",
    "condition": "会长且目标不是自己",
    "feedbackEffect": "fx.press.scale_096",
    "resultType": "popup",
    "resultState": "guild.role_permissions",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild.permission_denied"
  },
  {
    "actionId": "guild.member.role.commit",
    "system": "工会",
    "sourceState": "guild.role_permissions",
    "control": "保存权限",
    "condition": "会长且权限组合有效",
    "feedbackEffect": "fx.contract.stamp",
    "resultType": "transaction",
    "resultState": "guild.role_saved",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild.role_invalid"
  },
  {
    "actionId": "guild.module.aid",
    "system": "工会",
    "sourceState": "guild.home",
    "control": "物资互助",
    "condition": "已加入协会且VIP证有效",
    "feedbackEffect": "fx.card.selected",
    "resultType": "inline_state",
    "resultState": "guild.aid",
    "popupTemplate": "none",
    "errorState": "guild.pass_expired"
  },
  {
    "actionId": "guild.module.mine",
    "system": "工会",
    "sourceState": "guild.home",
    "control": "联合开采",
    "condition": "已加入协会且VIP证有效",
    "feedbackEffect": "fx.card.selected",
    "resultType": "inline_state",
    "resultState": "guild.passive_mine",
    "popupTemplate": "none",
    "errorState": "guild.pass_expired"
  },
  {
    "actionId": "guild.mine.collect",
    "system": "工会",
    "sourceState": "guild.passive_mine",
    "control": "领取矿石",
    "condition": "自动产出计时完成且有可领取矿石",
    "feedbackEffect": "fx.reward.burst",
    "resultType": "transaction",
    "resultState": "guild.mine_reward",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "guild.mine_not_ready"
  },
  {
    "actionId": "guild.module.shop",
    "system": "工会",
    "sourceState": "guild.home",
    "control": "协会商店",
    "condition": "已加入协会",
    "feedbackEffect": "fx.card.selected",
    "resultType": "navigation",
    "resultState": "guild_shop.home",
    "popupTemplate": "none",
    "errorState": "guild.not_joined"
  },
  {
    "actionId": "guild_apply.guild.select",
    "system": "工会申请",
    "sourceState": "guild_apply.list",
    "control": "工会列表卡",
    "condition": "始终可用",
    "feedbackEffect": "fx.card.selected",
    "resultType": "popup",
    "resultState": "guild_apply.detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "none"
  },
  {
    "actionId": "guild_apply.submit",
    "system": "工会申请",
    "sourceState": "guild_apply.detail",
    "control": "申请加入",
    "condition": "VIP证有效且挖掘深度达到门槛且未加入其他协会",
    "feedbackEffect": "fx.contract.stamp",
    "resultType": "transaction",
    "resultState": "guild_apply.submitted",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_apply.requirement_failed"
  },
  {
    "actionId": "guild_apply.pass.activate_ad",
    "system": "工会申请",
    "sourceState": "guild_apply.pass_required",
    "control": "看广告激活VIP证",
    "condition": "广告完成",
    "feedbackEffect": "fx.ad.badge_pulse",
    "resultType": "transaction",
    "resultState": "guild_apply.list",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "common.ad_unavailable"
  },
  {
    "actionId": "guild_apply.create.open",
    "system": "工会申请",
    "sourceState": "guild_apply.list",
    "control": "创建工会",
    "condition": "挖掘深度>=100米且金币>=10000且VIP证有效",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "popup",
    "resultState": "guild_apply.create_confirm",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_apply.create_requirement_failed"
  },
  {
    "actionId": "guild_apply.create.commit",
    "system": "工会申请",
    "sourceState": "guild_apply.create_confirm",
    "control": "支付10000金币创建",
    "condition": "名称有效且再次校验深度、金币、VIP证",
    "feedbackEffect": "fx.contract.stamp",
    "resultType": "transaction",
    "resultState": "guild.home_president",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_apply.name_or_resource_changed"
  },
  {
    "actionId": "guild_apply.cancel_application",
    "system": "工会申请",
    "sourceState": "guild_apply.submitted",
    "control": "撤回申请",
    "condition": "申请仍在审核",
    "feedbackEffect": "fx.press.red_flash",
    "resultType": "transaction",
    "resultState": "guild_apply.list",
    "popupTemplate": "common.dialog.warning",
    "errorState": "guild_apply.status_changed"
  },
  {
    "actionId": "guild_shop.contribute.open",
    "system": "工会商店",
    "sourceState": "guild_shop.home",
    "control": "金币贡献",
    "condition": "金币>0",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "popup",
    "resultState": "guild_shop.contribute",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_shop.coin_insufficient"
  },
  {
    "actionId": "guild_shop.contribute.minus",
    "system": "工会商店",
    "sourceState": "guild_shop.contribute",
    "control": "减号",
    "condition": "金额>最小步长",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "guild_shop.contribute_changed",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_shop.amount_min"
  },
  {
    "actionId": "guild_shop.contribute.plus",
    "system": "工会商店",
    "sourceState": "guild_shop.contribute",
    "control": "加号",
    "condition": "金额<金币余额",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "guild_shop.contribute_changed",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_shop.coin_insufficient"
  },
  {
    "actionId": "guild_shop.contribute.commit",
    "system": "工会商店",
    "sourceState": "guild_shop.contribute",
    "control": "贡献金币",
    "condition": "二次校验金额与余额",
    "feedbackEffect": "fx.coin.to_contribution",
    "resultType": "transaction",
    "resultState": "guild_shop.contribution_received",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "guild_shop.coin_changed"
  },
  {
    "actionId": "guild_shop.item.select",
    "system": "工会商店",
    "sourceState": "guild_shop.home",
    "control": "商品卡",
    "condition": "商品已解锁且未达限购",
    "feedbackEffect": "fx.card.selected",
    "resultType": "popup",
    "resultState": "guild_shop.exchange_confirm",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "guild_shop.item_locked_or_sold_out"
  },
  {
    "actionId": "guild_shop.item.exchange",
    "system": "工会商店",
    "sourceState": "guild_shop.exchange_confirm",
    "control": "兑换",
    "condition": "贡献值足够且库存未变",
    "feedbackEffect": "fx.reward.burst",
    "resultType": "transaction",
    "resultState": "guild_shop.exchange_reward",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "guild_shop.contribution_or_stock_changed"
  },
  {
    "actionId": "warehouse.item.owned",
    "system": "仓库",
    "sourceState": "warehouse.catalog",
    "control": "已拥有物品卡",
    "condition": "数量>0",
    "feedbackEffect": "fx.card.selected",
    "resultType": "popup",
    "resultState": "warehouse.item_detail",
    "popupTemplate": "common.sheet.info",
    "errorState": "warehouse.item_changed"
  },
  {
    "actionId": "warehouse.item.unowned",
    "system": "仓库",
    "sourceState": "warehouse.catalog",
    "control": "未拥有黑底物品卡",
    "condition": "数量=0",
    "feedbackEffect": "fx.silhouette.reveal_hint",
    "resultType": "inline_state",
    "resultState": "warehouse.catalog",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "warehouse.item.sell",
    "system": "仓库",
    "sourceState": "warehouse.item_detail",
    "control": "出售",
    "condition": "数量>0",
    "feedbackEffect": "fx.press.gold_flash",
    "resultType": "popup",
    "resultState": "warehouse_sell.quantity",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "warehouse.item_changed"
  },
  {
    "actionId": "warehouse.scroll",
    "system": "仓库",
    "sourceState": "warehouse.catalog",
    "control": "竖向拖动四列网格",
    "condition": "物品超出一屏",
    "feedbackEffect": "fx.list.inertia",
    "resultType": "inline_state",
    "resultState": "warehouse.catalog_scrolled",
    "popupTemplate": "none",
    "errorState": "none"
  },
  {
    "actionId": "warehouse_sell.amount.minus",
    "system": "仓库售卖",
    "sourceState": "warehouse_sell.quantity",
    "control": "减号",
    "condition": "出售数量>1",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "warehouse_sell.quantity_changed",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "warehouse_sell.amount_min"
  },
  {
    "actionId": "warehouse_sell.amount.plus",
    "system": "仓库售卖",
    "sourceState": "warehouse_sell.quantity",
    "control": "加号",
    "condition": "出售数量<当前拥有数量",
    "feedbackEffect": "fx.value.tick",
    "resultType": "inline_state",
    "resultState": "warehouse_sell.quantity_changed",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "warehouse_sell.amount_max"
  },
  {
    "actionId": "warehouse_sell.amount.max",
    "system": "仓库售卖",
    "sourceState": "warehouse_sell.quantity",
    "control": "最大",
    "condition": "拥有数量>0",
    "feedbackEffect": "fx.value.snap",
    "resultType": "inline_state",
    "resultState": "warehouse_sell.quantity_max",
    "popupTemplate": "common.dialog.transaction",
    "errorState": "warehouse.item_changed"
  },
  {
    "actionId": "warehouse_sell.commit",
    "system": "仓库售卖",
    "sourceState": "warehouse_sell.quantity",
    "control": "出售",
    "condition": "数量有效且库存未变",
    "feedbackEffect": "fx.coin.fly",
    "resultType": "transaction",
    "resultState": "warehouse_sell.reward",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "warehouse_sell.inventory_changed"
  },
  {
    "actionId": "warehouse_sell.reward.dismiss",
    "system": "仓库售卖",
    "sourceState": "warehouse_sell.reward",
    "control": "弹窗遮罩或系统返回",
    "condition": "交易已写入存档",
    "feedbackEffect": "fx.popup.fade_out",
    "resultType": "inline_state",
    "resultState": "warehouse.catalog",
    "popupTemplate": "common.reward.horizontal",
    "errorState": "none"
  }
];
