/* Standalone review UI: all business actions go through ReviewEngine. */
(()=>{'use strict';
const {ReviewEngine,ITEMS,GOODS}=MoleReview;const engine=new ReviewEngine();window.review=engine;
const $=id=>document.getElementById(id);let busy=false,timer,chosen=null,safe=false,scrollTimer,inventoryIntentUntil=0;
const esc=x=>String(x??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const num=x=>Number(x).toLocaleString('zh-CN');const img=(id,cls='icon',folder='icons')=>id?`<img class="${cls}" src="${id==='mole_explorer'&&cls===''?'assets/visual/mole-full.png':`assets/${folder}/${id}.png`}" alt="">`:'<span class="unknown-item" aria-label="未发现物品">?</span>';
const btn=(text,id,p='',cls='',disabled=false)=>`<button type="button" class="game-btn ${cls}" data-action="${id}" data-payload="${esc(p)}" ${disabled?'disabled':''}>${text}</button>`;
// Shared close control: cancel/back only, never commit the pending transaction.
const closeButton=()=>'';
// Functional screens are dialogs above a non-interactive, live home underlay.
// Keep actual mining full-screen, and keep ReviewEngine navigation unchanged.
const homeUnderlay=document.createElement('div');homeUnderlay.id='home-underlay';homeUnderlay.inert=true;homeUnderlay.setAttribute('aria-hidden','true');
const screenShade=document.createElement('div');screenShade.id='screen-shade';screenShade.dataset.screenDismiss='true';screenShade.setAttribute('aria-hidden','true');
$('phone').prepend(homeUnderlay,screenShade);
const dismissHint=(action='nav.back')=>`<button type="button" class="popup-dismiss-hint" data-action="${action}" ${busy?'disabled':''}>点击任意区域关闭。</button>`;
const screenHint=document.createElement('div');screenHint.id='screen-dismiss-hint';$('phone').append(screenHint);
const row=(label,value)=>`<div class="stat-line"><span>${label}</span><strong>${value}</strong></div>`;
const paper=html=>`<div class="paper">${html}</div>`;
const title={home:'老鼠巷矿洞',gameplay:'矿层探索',ranking:'排行榜',debt:'偿还债务',lending:'矿区信贷所',notes:'矿区信贷所',guild:'矿工协会',members:'成员名单',manage:'协会管理',aid:'物资互助',mine:'联合开采',shop:'协会商店',apply:'矿工协会',warehouse:'仓库图鉴',audit:'申请审核'};
const systems=[['主玩法','gameplay'],['主界面','home'],['排行榜','ranking'],['放贷 / 还款','lending'],['工会','guild'],['工会申请','apply'],['工会商店','shop'],['仓库','warehouse'],['仓库售卖','sell']];
const extraActions=[['extra.aid.request','申请互助物资','已加入协会，VIP证有效，无进行中申请'],['extra.aid.donate','捐赠互助物资','铁矿石至少 5 个，未重复捐赠'],['extra.aid.collect','领取互助物资','物资已送达且未领取'],['extra.notice.open','编辑协会公告','会长权限'],['extra.notice.save','保存协会公告','会长权限，公告 1–60 字'],['extra.audit.open','进入申请审核','会长权限'],['extra.audit.accept','通过入会申请','会长权限，申请未处理'],['extra.audit.reject','拒绝入会申请','会长权限，申请未处理']].map(([actionId,control,condition])=>({actionId,control,condition,system:'工会'}));
window.REVIEW_EXTRA_ACTIONS=extraActions;
const modalNames={mission:'当前目标',onlineConfirm:'领取奖励',checkin:'签到',achievements:'成就',profile:'角色档案',profileAvatar:'选择头像',profileNickname:'修改昵称',wardrobe:'衣橱',guildManage:'协会管理',guildMembers:'成员管理',guildAudit:'申请审核',workshop:'矿镐强化',beauty:'美容院',buildingUpgrade:'建筑升级',guildGrowth:'协会成长',aidRequest:'发布物资申请',levels:'选择矿层',levelDetails:'产出详情',wealth:'财富等级',pass:'VIP',lockedLevel:'矿层未解锁',rankingRules:'排名规则',energy:'铲子能量',tutorial:'挖矿教学',success:'开采完成',failed:'铲子用完了',reward:'恭喜获得',repay:'确认偿还债务',repaid:'还款完成',debtCleared:'债务已还清',loan:'签署借据',note:'借据详情',loanHistory:'已结算借据',historyDetail:'结算详情',slotLocked:'槽位未解锁',member:'成员详情',kick:'移出成员？',role:'调整职务',guildDetail:'协会详情',applied:'申请已提交',createGuild:'创建协会',contribute:'金币贡献',exchange:'兑换商品',item:'物品详情',source:'发现线索',sell:'出售物品',notice:'编辑公告'};
function body(){const s=engine.s;const production=window.productionUI?.screen({s,engine,img,btn,row,paper,num,esc});if(production!==undefined)return production;switch(s.page){
case 'home':{const overdue=s.notes.find(n=>n.status==='runaway'),mature=s.notes.find(n=>n.status==='matured'),active=s.notes.find(n=>n.status==='active');
 const status=s.debt>0?`<b>剩余债务 ${num(s.debt)}</b><div class="sub">手动还清债务，解锁放贷业务</div>${btn('前往还款','home.debt.open')}`:overdue?`<b class="bad">借款人跑路 · ${overdue.name}</b><div class="sub">本金损失 ${num(overdue.principal)}</div>${btn('了解','home.loan.runaway')}`:mature?`<b class="good">借据已到期 · ${mature.name}</b>${btn('领取本息','home.loan.matured')}`:active?`<b>放贷进行中 · ${active.name}</b><div class="sub">剩余 ${Math.max(0,active.due-s.clock)} 小时</div>${btn('查看借据','home.loan.active')}`:`<b>放贷业务</b><div class="sub">${engine.pass()?'VIP证有效':'VIP证已过期'}</div>${btn('进入放贷','home.lending.open')}`;
 return `${paper(`<div class="row spread"><div class="grow">${status}</div>${img('loan_contract','avatar')}</div>`)}<div class="hero">${img('mole_explorer','','avatars')}</div><div class="entry-grid">${btn(img('trophy')+' 排行榜','home.ranking.open')}${btn(img('warehouse')+' 仓库','home.warehouse.open')}${btn(img('guild_shield')+' 矿工协会','home.guild.open')}${btn('VIP证 · '+(engine.pass()?'有效':'已过期'),'home.miner_pass')}</div><div class="row">${btn('财富 Lv.'+s.wealth,'home.wealth.open','','secondary grow')}${btn('交易所 · 未开放','home.locked_feature','','secondary grow')}</div>${btn(`第 ${s.level} 关 · 开始挖矿`,'home.play')}`;}
case 'gameplay':return `<div class="row">${paper(`<strong>第 ${s.level} 关</strong>`)}${paper(`<strong>宝藏 ${engine.found()}/${s.n}</strong>`)}</div>${btn(img('shovel_energy')+` × ${s.shovels}`,'gameplay.energy.info','','secondary')}<div class="sub" style="text-align:center">单击插旗 · 双击挖掘</div><div class="board" style="--n:${s.n}">${Array.from({length:s.n*s.n},(_,i)=>`<button class="tile ${s.dug.includes(i)?'dug':''} ${s.flags.includes(i)?'flagged':''} ${s.hint===i?'hint':''}" data-tile="${i}" aria-label="第 ${Math.floor(i/s.n)+1} 行第 ${i%s.n+1} 列${s.dug.includes(i)?'已挖掘':''}">${s.dug.includes(i)&&engine.treasures().includes(i)?img(engine.treasureItem(i)[0],''):''}</button>`).join('')}</div><div class="grow"></div>${btn(img('radar_ad')+' 雷达指南 · 广告','gameplay.radar.watch_ad')}`;
case 'ranking':return `<div class="tabs">${btn('财富榜','ranking.tab.wealth','',''+(s.rank==='wealth'?'selected':'secondary'))}${btn('深度榜','ranking.tab.depth','',''+(s.rank==='depth'?'selected':'secondary'))}${btn('规则','ranking.rules.open','','secondary')}</div><div class="scroll stack">${s.emptyRank?'<div class="paper empty">暂无排名</div>':Array.from({length:16},(_,i)=>paper(`<div class="rank-row"><b>${i+1}</b>${img(['mole_veteran','mole_foreman','mole_explorer'][i%3],'avatar','avatars')}<span class="grow">${['老矿灯','铜轮队长','岩仔','阿铜'][i%4]}${i>=4?' '+(i+1):''}</span><strong>${s.rank==='wealth'?num(999999-i*32100):num(8000-i*300)+'米'}</strong></div>`)).join('')}</div>${paper(`<div class="row spread"><strong>你 · ${s.emptyRank?'10,000+':'128'}</strong><b>${s.rank==='wealth'?num(s.coins-s.debt):s.depth+'米'}</b></div>`)}`;
case 'debt':return `<div class="grow stack">${paper(`<p>尚待偿还</p><div class="balance bad">${num(s.debt)}</div><p class="sub">还清债务，持有效VIP证即可放贷</p>`)}${paper(`<p>本次偿还</p>${quantity('debt.amount',Math.min(s.coins,s.debt),100)}${row('剩余金币',num(s.coins-s.amount))}`)}</div>${btn(s.debt===0?'进入放贷':'偿还 '+num(s.amount)+' 金币',s.debt===0?'home.lending.open':'debt.repay.open','','',s.debt>0&&s.amount<=0)}`;
case 'lending':case 'notes':{const tabs=`<div class="tabs">${btn('放贷大厅','lending.tab.hall','',''+(s.page==='lending'?'selected':'secondary'))}${btn('我的借据','lending.tab.notes','',''+(s.page==='notes'?'selected':'secondary'))}</div>`;if(s.page==='lending')return tabs+`<div class="row spread"><span class="sub">${Math.max(0,s.refreshAt-s.clock)} 小时后刷新</span>${btn('立即刷新 · 广告','lending.refresh.ad','','small')}</div><div class="scroll stack slots">${s.offers.map(o=>`<button class="note paper" data-action="${o.signed?'lending.candidate.loaned':'lending.candidate.select'}" data-payload="${o.id}">${img(o.avatar,'avatar','avatars')}<div class="grow"><strong>${o.name}</strong><div class="sub">本金 ${num(o.principal)} · ${o.hours} 小时</div><div class="good">${o.signed?'已放贷':'利率 '+Math.round(o.rate*100)+'%'}</div></div></button>`).join('')}</div>`;const notes=engine.activeNotes();return tabs+`<div class="row spread"><span class="sub">借据 ${notes.length} / ${engine.slots()}</span>${btn('结算记录','lending.history.open','','small secondary')}</div><div class="scroll stack slots">${Array.from({length:5},(_,i)=>{const n=notes[i];if(n)return `<button class="note paper" data-action="lending.note.${n.status==='active'?'active':n.status==='matured'?'matured':'runaway'}.open" data-payload="${n.id}">${img(n.avatar,'avatar','avatars')}<div class="grow"><strong>${n.name}</strong><div class="sub">本金 ${num(n.principal)} · 利息 ${num(n.interest)}</div><b class="${n.status==='runaway'?'bad':'good'}">${n.status==='active'?`进行中 · ${Math.max(0,n.due-s.clock)} 小时`:n.status==='matured'?'到期 · 领取本息':'跑路 · 了解'}</b></div></button>`;return `<button class="note paper ${i>=engine.slots()?'locked':''}" data-action="lending.slot.${i>=engine.slots()?'locked':'empty'}"><div class="grow" style="text-align:center"><strong>${i>=engine.slots()?'尚未解锁':'空闲借据槽位'}</strong><div class="sub">${i>=engine.slots()?'财富 Lv.11 解锁':'选择新的借款人'}</div></div></button>`;}).join('')}</div>`;}
case 'guild':return `${paper(`<div class="row">${img('guild_shield','avatar')}<div class="grow"><strong>${esc(s.guildName)}</strong><p class="sub">${esc(s.notice)}</p></div></div>`)}<div class="row">${btn('成员 '+s.members.length+'/30','guild.members.open','','secondary grow')}${s.president?btn('管理','guild.manage.open','','secondary'):''}</div><div class="stack grow">${btn(img('ore_iron','avatar')+' 物资互助','guild.module.aid','','grow')}${btn(img('treasure_chest','avatar')+' 联合开采','guild.module.mine','','grow')}${btn(img('shop','avatar')+' 协会商店','guild.module.shop','','grow')}</div>${!engine.pass()?'<div class="paper bad">VIP证已过期，部分权益暂停</div>':''}`;
case 'members':return `<div class="scroll stack">${s.members.map(m=>`<button class="paper member" data-action="guild.member.open" data-payload="${m.id}">${img(m.avatar,'avatar','avatars')}<div class="grow"><strong>${m.name}</strong><div class="sub">${m.role}</div></div><span class="${m.expired?'bad':'good'}">${m.expired?'VIP证过期':'有效'}</span></button>`).join('')}</div>`;
case 'manage':return `<div class="stack">${btn('成员管理','guild.members.open')}${btn('申请审核','extra.audit.open')}${btn('编辑公告','extra.notice.open')}${paper('<p>职务权限在成员详情中调整。</p>')}</div>`;
case 'audit':return s.auditDone?paper('<p class="empty">申请已处理</p>'):paper(`<div class="row">${img('mole_rookie','avatar','avatars')}<div><strong>矿工小石</strong><p>深度 350 米 · VIP证有效</p></div></div><div class="actions">${btn('拒绝','extra.audit.reject','','secondary')}${btn('通过申请','extra.audit.accept')}</div>`);
case 'aid':return `<div class="stack">${paper(`<h3>我的物资申请</h3><p>铁矿石 × 5</p>${btn(s.aidReady?'领取物资':s.aidPosted?'等待成员捐赠':'申请物资',s.aidReady?'extra.aid.collect':'extra.aid.request','','',s.aidPosted&&!s.aidReady)}`)}${paper(`<h3>岩仔的申请</h3><div class="row">${img('ore_iron','avatar')}<span>铁矿石 × 5</span></div><p class="sub">捐赠可获得 20 贡献</p>${btn(s.aidDonated?'已捐赠':'捐赠 5 个','extra.aid.donate','','',s.aidDonated)}`)}</div>`;
case 'mine':return `${paper(`<div style="text-align:center">${img('treasure_chest','avatar')}<h3>联合矿井</h3><p>${s.mineDue<=s.clock?'本轮开采完成':`剩余 ${s.mineDue-s.clock} 小时`}</p><progress value="${s.mineDue<=s.clock?100:Math.max(0,100-(s.mineDue-s.clock)/6*100)}" max="100"></progress></div>`)}${paper(row('铁矿石','×12')+row('铜矿石','×5')+row('银矿石','×3'))}<div class="grow"></div>${btn('领取矿石','guild.mine.collect')}`;
case 'apply':return `<div class="scroll stack">${[s.guildName,'深层勘探团'].map((n,i)=>`<button class="paper member" data-action="guild_apply.guild.select" data-payload="${i}">${img('guild_shield','avatar')}<div><strong>${n}</strong><p class="sub">${i?1000:100} 米深度 · ${i?'28':'18'}/30 人</p></div></button>`).join('')}${s.application?paper(`<p class="good">申请审核中</p>${btn('撤回申请','guild_apply.cancel_application','','secondary')}`):''}</div>${btn('创建协会','guild_apply.create.open')}`;
case 'shop':return `${paper(`<div class="row spread"><div>可用贡献 <b class="good">${num(s.contribution)}</b><p class="sub">金币贡献可换取贡献值</p></div>${btn('金币贡献','guild_shop.contribute.open','','small')}</div>`)}<div class="scroll"><div class="mini-grid">${GOODS.map((g,i)=>`<div class="paper product"><div class="row">${img(g[0],'')}<strong>${g[1]}</strong></div><p>${g[2]} 贡献 · 剩余 ${s.stock[i]}</p>${btn(s.stock[i]?'兑换':'已售罄','guild_shop.item.select',i,'',!s.stock[i])}</div>`).join('')}</div></div>`;
case 'warehouse':return `<div class="row spread"><strong>收集 ${s.inventory.filter(n=>n>0).length}/${ITEMS.length}</strong><span class="sub">全部物品</span></div><div class="scroll" id="inventory-scroll"><div class="item-grid">${ITEMS.map((it,i)=>`<button class="item-card ${s.inventory[i]?'':'unowned'}" data-action="warehouse.item.${s.inventory[i]?'owned':'unowned'}" data-payload="${i}"><b class="quality">${it[2]}</b>${img(it[0],'')}<strong>${s.inventory[i]?it[1]:'尚未拥有'}</strong><span>${s.inventory[i]?'× '+num(s.inventory[i]):it[4]+'米出现'}</span></button>`).join('')}</div></div>`;
default:return paper('页面未实现');}}
function quantity(prefix,max,step=1){const s=engine.s;return `<div class="quantity">${btn('−',prefix+'.minus','','small',s.amount<=step)}<output>${num(s.amount)}</output>${btn('+',prefix+'.plus','','small',s.amount>=max)}${prefix!=='guild_shop.contribute'?btn('最大',prefix+'.max','','small',max<=0):''}</div>`;}
function modalBody(){const s=engine.s;const production=window.productionUI?.modal({s,engine,img,btn,row,paper,num,esc,chosen});if(production!==undefined)return production;const it=ITEMS[s.selectedItem],n=engine.note(),m=engine.member();switch(s.modal){
case 'levels':return `${row('当前矿层',`第 ${s.level} 关`)}${row('棋盘',`${s.n} × ${s.n}`)}${row('初始铲子',s.n+3)}<div class="actions">${btn('上一关','gameplay.level.previous','','secondary')}${btn('下一关','gameplay.level.next')}</div><div class="actions">${btn('未解锁矿层','gameplay.level.locked','','secondary')}</div><div class="actions">${btn('支付 '+num(engine.levelInfo().coinCost)+' 金币进入','gameplay.level.enter','','',s.coins<engine.levelInfo().coinCost)}</div>`;
case 'lockedLevel':return `<p>财富 Lv.9 解锁更深矿层</p>${row('当前财富等级','Lv.'+s.wealth)}`;
case 'wealth':return `${row('财富等级','Lv.'+s.wealth)}${row('当前金币',num(s.coins))}${row('剩余债务',num(s.debt))}${row('最大深度',s.depth+' 米')}`;
case 'pass':return `<div style="text-align:center">${img('loan_contract','avatar')}<p class="${engine.pass()?'good':'bad'}">${engine.pass()?`有效期剩余 ${Math.ceil(s.passUntil-s.clock)} 小时`:'VIP证已过期'}</p></div><p>放贷与协会权益需要有效VIP证</p><div class="actions">${btn((engine.pass()?'续期':'激活')+' 3 天 · 广告',chosen?.includes('lending.pass')?'lending.pass.activate_ad':chosen?.includes('guild_apply.pass')?'guild_apply.pass.activate_ad':'home.miner_pass.renew_ad')}</div>`;
case 'rankingRules':return '<p>财富榜按财富数值排序，深度榜按最深挖掘记录排序。</p><p>展示前 100 名；本人名次固定显示。榜外显示 10,000+。</p>';
case 'energy':return `<p>每局初始铲子 = 单边格数 + 3。</p><p>每次挖掘消耗 1 把，无论是否找到宝藏。插旗与重复点击不消耗。</p>${row('本局初始',s.n+3)}${row('当前剩余',s.shovels)}`;
case 'tutorial':return `<p>${s.tutorial===1?'单击格子插旗，标记你的判断。':'双击格子挖掘，每次消耗 1 把铲子。'}</p><div class="actions">${btn(s.tutorial===1?'下一步':'开始挖掘','gameplay.tutorial.next')}</div>`;
case 'success':return `<div class="game-result-copy">${img('treasure_chest','game-result-art')}<h3>宝藏已收集</h3><p>已发现全部 ${s.n} 个宝藏</p><div class="paper">收下战利品，继续向更深处探索</div></div><div class="actions">${btn('领取全部','gameplay.success.collect')}</div>`;
case 'failed':return `<div class="game-result-copy">${img('shovel_energy','game-result-art')}<h3>还有宝藏等待发现</h3><p>剩余 ${s.n-engine.found()} 个宝藏</p><div class="paper">补充矿铲，继续本次探索</div></div><div class="actions">${btn('复活 +2 铲 · 广告','gameplay.fail.revive')}</div><div class="actions">${btn('重开 · '+num(engine.levelInfo().coinCost)+' 金币','gameplay.fail.restart','','secondary',s.coins<engine.levelInfo().coinCost)}</div>`;
case 'reward':if(!s.reward?.length)return '<div class="reward-empty">暂无奖励</div>';return `<div class="reward-list">${(s.reward||[]).map(r=>`<div class="reward-item">${img(r[0],'')}<div>${r[1]}</div><b>× ${num(r[2])}</b></div>`).join('')}</div>`;
case 'repay':return row('本次偿还',num(s.snapshot?.amount))+row('偿还后债务',num(s.debt-(s.snapshot?.amount||0)))+`<div class="actions">${btn('偿还','debt.repay.commit')}</div>`;
case 'repaid':return `<p class="good">还款成功</p>${row('剩余债务',num(s.debt))}`;
case 'debtCleared':return `<p class="good">债务已还清</p><p>有效VIP证可开启放贷业务</p><div class="actions">${btn('进入放贷','home.lending.open')}</div>`;
case 'loan':{const o=s.offers[s.selectedOffer];return `<div class="row">${img(o.avatar,'avatar','avatars')}<strong>${o.name}</strong></div>${row('本金',num(o.principal))}${row('利率',Math.round(o.rate*100)+'%')}${row('期限',o.hours+' 小时')}${row('到期应收',num(Math.round(o.principal*(1+o.rate))))}<p class="sub">借款人可能跑路，损失本金</p><div class="actions">${btn('签署借据并放贷','lending.loan.commit')}</div>`;}
case 'note':if(!n)return '<p>借据已不存在</p>';return `<div class="row">${img(n.avatar,'avatar','avatars')}<strong>${n.name}</strong></div>${row('本金',num(n.principal))}${row('利息',num(n.interest))}${n.status==='active'?row('剩余',Math.max(0,n.due-s.clock)+' 小时'):''}${n.status==='matured'?row('本息合计',num(n.principal+n.interest))+`<div class="actions">${btn('领取本息','lending.note.collect')}</div>`:n.status==='runaway'?`<p class="bad">借款人跑路，本金损失 ${num(n.principal)}</p><div class="actions">${btn('确认损失','lending.note.runaway.ack','','danger')}</div>`:''}`;
case 'loanHistory':return s.history.map((h,i)=>btn(h.name+' · '+(h.status==='collected'?'已回款':'损失已记录'),'lending.history.item',i,'secondary')).join('');
case 'historyDetail':{const h=s.history[s.historyIndex||0];return h?row('借款人',h.name)+row('本金',num(h.principal))+row('结算结果',h.status==='collected'?'已回款':'本金损失'):'';}
case 'slotLocked':return '<p>财富 Lv.11 解锁第 5 个借据槽位</p>';
case 'member':if(!m)return '<p>成员已离开</p>';return `<div class="row">${img(m.avatar,'avatar','avatars')}<strong>${m.name}</strong></div>${row('职务',m.role)}${row('VIP证',m.expired?'已过期':'有效')}${s.president&&m.id!==0?`<div class="actions">${btn('调整职务','guild.member.role.open','','secondary')}${btn('移出协会','guild.member.kick.open','','danger')}</div>`:''}`;
case 'kick':return `<p>将 ${m?.name||'该成员'} 移出协会？</p><p class="sub">移出后需重新申请加入。</p><div class="actions">${btn('取消','nav.back','','secondary')}${btn('移出成员','guild.member.kick.commit','','danger')}</div>`;
case 'role':return `<label>职务<select class="game-input" data-field="roleDraft">${['成员','管理员','副会长'].map(v=>`<option ${s.roleDraft===v?'selected':''}>${v}</option>`).join('')}</select></label>${[['audit','审核申请'],['notice','编辑公告'],['aid','处理互助'],['kick','移出普通成员']].map(([key,label])=>`<label class="check-row"><input type="checkbox" data-permission="${key}" ${s.permissionDraft?.[key]?'checked':''}>${label}</label>`).join('')}<div class="actions">${btn('保存权限','guild.member.role.commit')}</div>`;
case 'guildDetail':return row('协会',s.selectedGuild?'深层勘探团':s.guildName)+row('要求深度',s.selectedGuild?'1,000 米':'100 米')+row('你的深度',s.depth+' 米')+row('VIP证',engine.pass()?'有效':'已过期')+`<div class="actions">${btn(!engine.pass()?'激活VIP证 · 广告':s.application?'申请审核中':'申请加入',!engine.pass()?'guild_apply.pass.activate_ad':'guild_apply.submit','','',engine.pass()&&(s.application||s.joined))}</div>`;
case 'applied':return `<p>等待协会审核</p><div class="actions">${btn('撤回申请','guild_apply.cancel_application','','secondary')}</div>`;
case 'createGuild':return `<label>协会名称<input class="game-input" data-field="guildDraft" maxlength="12" value="${esc(s.guildDraft)}"></label>${row('创建费用','10,000 金币')}<div class="actions">${btn('支付 10,000 金币创建','guild_apply.create.commit')}</div>`;
case 'contribute':return `${row('可用金币',num(s.coins))}${quantity('guild_shop.contribute',s.coins,100)}${row('可获得贡献',num(Math.floor(s.amount/10)))}<div class="actions">${btn('贡献金币','guild_shop.contribute.commit')}</div>`;
case 'exchange':{const g=GOODS[s.selectedGood];return `<div class="row">${img(g[0],'avatar')}<strong>${g[1]}</strong></div>${row('花费贡献',g[2])}${row('可用贡献',s.contribution)}${row('剩余限购',s.stock[s.selectedGood])}<div class="actions">${btn('兑换','guild_shop.item.exchange')}</div>`;}
case 'item':case 'source':return `<div class="row">${img(it[0],'avatar')}<strong>${it[1]} · ${it[2]}</strong></div>${row('出现深度',it[4]+' 米')}${s.modal==='item'?row('拥有',num(s.inventory[s.selectedItem]))+`<div class="actions">${btn('出售','warehouse.item.sell')}</div>`:'<p>在对应深度矿层挖掘发现</p>'}`;
case 'sell':return `<div class="row">${img(it[0],'avatar')}<strong>${it[1]} · ${it[2]}</strong></div>${row('单价',num(it[3])+' 金币')}${row('拥有',num(s.inventory[s.selectedItem]))}${quantity('warehouse_sell.amount',s.inventory[s.selectedItem])}${row('预计获得',num(s.amount*it[3])+' 金币')}<div class="actions">${btn('出售','warehouse_sell.commit')}</div>`;
case 'notice':return `<label>协会公告<textarea class="game-input" rows="4" maxlength="60" data-field="noticeDraft">${esc(s.noticeDraft)}</textarea></label><div class="actions">${btn('保存公告','extra.notice.save')}</div>`;
default:return '<p>缺少业务内容，不能验收</p>';}}
function render(){clearTimeout(timer);$('toast').classList.remove('visible');const s=engine.s;if(s.page==='guild')s.page=s.joined?'shop':'apply';document.getElementById('phone').dataset.modal=s.modal||'';window.productionUI?.compare(s);const self=s.members.find(m=>m.id===0);if(self){self.expired=!engine.pass();self.role=s.president?'会长':'成员';}const oldScroll=$('game').querySelector('.scroll')?.scrollTop||0;const oldPage=$('game').dataset.page;$('game').dataset.page=s.page;
 const isPopup=!['home','gameplay'].includes(s.page);$('phone').dataset.presentation=isPopup?'popup':s.page;
 homeUnderlay.hidden=!isPopup;screenShade.hidden=!isPopup;
 screenHint.innerHTML=isPopup&&!s.modal?dismissHint():'';screenHint.hidden=!isPopup||!!s.modal;
 homeUnderlay.innerHTML=isPopup?(window.productionUI?.screen({s:{...s,page:'home',modal:null},engine,img,btn,row,paper,num,esc})||''):'';
 $('game').inert=!!s.modal||busy;$('game').setAttribute('role',isPopup?'dialog':'region');$('game').setAttribute('aria-label',title[s.page]);
 if(isPopup&&!s.modal)$('game').setAttribute('aria-modal','true');else $('game').removeAttribute('aria-modal');
 const customHud=window.productionUI?.hud?.({s,img,num});$('game').innerHTML=(customHud!==undefined?customHud:`<div class="hud"><div>${img('coin')} ${num(s.coins)}</div></div>`)+`<h2 class="page-title">${title[s.page]}</h2>${body()}`+(s.page==='gameplay'?closeButton(title[s.page],'nav.back',busy||!!s.modal):'');
 if(oldPage===s.page&&$('game').querySelector('.scroll'))$('game').querySelector('.scroll').scrollTop=oldScroll;
 const modalCornerBack=s.modal==='pass'&&s.passReturnModal==='checkin'?'<button type="button" class="modal-corner-back" data-action="rewards.pass.back" aria-label="返回签到"></button>':s.modal==='checkin'&&s.rewardTab==='online'?'<button type="button" class="modal-corner-back" data-action="rewards.tab" data-payload="daily" aria-label="返回签到"></button>':'';
 $('overlays').innerHTML=(s.modal?`<div class="modal-shade" data-dismiss="true"><section class="modal" role="dialog" aria-modal="true" aria-label="${modalNames[s.modal]}"><h2>${modalNames[s.modal]}</h2>${modalCornerBack}<div class="modal-content">${modalBody()}</div>${dismissHint(s.modal==='reward'?(s.rewardReturn==='home'?'gameplay.reward.dismiss':'warehouse_sell.reward.dismiss'):'nav.back')}</section></div>`:'')+(busy?'<div class="busy-shade"><span>处理中…</span></div>':'')+(safe?'<div class="safe-marker"></div>':'');
 $('systems').innerHTML=systems.map(([name,page])=>`<button data-route="${page}" class="${s.page===page?'active':''}">${name}</button>`).join('');
 const action=(window.REVIEW_ACTIONS||[]).find(a=>a.actionId===chosen);$('inspector').innerHTML=`<b>${title[s.page]}${s.modal?' → '+modalNames[s.modal]:''}</b><p>${esc(engine.last.detail)}</p>${action?`<b>正在检查：${esc(action.control)}</b><p>前置条件：${esc(action.condition)}</p><code>${action.actionId}</code>`:''}<hr><div>金币 ${num(s.coins)}<br>债务 ${num(s.debt)} · 贡献 ${s.contribution}<br>VIP证 ${engine.pass()?'有效':'过期'} · ${s.joined?'已加入协会':'未加入协会'}</div><p>已操作基线 ${Object.keys(s.seen).filter(k=>REVIEW_ACTIONS.some(a=>a.actionId===k)).length}/84，含成功与异常。仅表示人工操作记录，不是自动验收率。</p>`;
 $('history').innerHTML=s.events.slice(0,25).map(e=>`<p><b>${e.ok?'成功':'异常'} · ${e.time}</b><br>${esc(e.detail)}<br><code>${esc(e.id)}</code></p>`).join('')||'<p>尚未操作</p>';
 actionList();$('ad-mode').value=s.adMode;$('tx-mode').value=s.txMode;
 window.BuildingUpgrade?.mount(s);
 window.LevelDepthRuler?.mount(s);
 window.BeautyUI?.mount();
 window.HomeVIPUI?.mount();
 window.VIPPassUI?.mount();
 $('home-status-fixture').value=({debt:'home.debt.open',cleared:'home.lending.open',active:'home.loan.active',matured:'home.loan.matured',runaway:'home.loan.runaway'})[HomeStatusCard.describe({s,engine}).id];
 const scroll=$('inventory-scroll');if(scroll){for(const event of ['wheel','touchmove','pointerdown','keydown'])scroll.addEventListener(event,()=>{inventoryIntentUntil=performance.now()+700;},{passive:true});scroll.addEventListener('scroll',()=>{if(s.modal||performance.now()>inventoryIntentUntil)return;clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{if(engine.s.modal)return;engine.result('warehouse.scroll',true,'四列物品列表已滚动');updateHistoryOnly();},250);});}
 if(chosen&&(window.REVIEW_EVIDENCE||[]).includes(chosen))$('inspector').insertAdjacentHTML('beforeend',`<a href="screenshots/states/${chosen}.png" target="_blank" rel="noopener">查看此动作的 720×1280 检查截图</a>`);
 const extra=extraActions.find(a=>a.actionId===chosen);if(extra)$('inspector').insertAdjacentHTML('beforeend',`<hr><b>${extra.control}</b><p>前置条件：${extra.condition}</p><code>${extra.actionId}</code><p><a href="screenshots/states/${extra.actionId}.png" target="_blank" rel="noopener">查看补充流程检查截图</a></p>`);
}
function updateHistoryOnly(){$('history').innerHTML=engine.s.events.slice(0,25).map(e=>`<p>${esc(e.detail)}</p>`).join('');}
function actionList(){const filter=$('action-system').value;const list=[...REVIEW_ACTIONS,...extraActions].filter(a=>!filter||a.system===filter);$('action-list').innerHTML=list.map(a=>`<button data-prepare="${a.actionId}" class="${engine.s.seen[a.actionId]?'seen':''}">${esc(a.control)}<br><span class="sub" style="font-size:11px">${a.system}${a.actionId.startsWith('extra.')?' · 补充流程':''} · ${engine.s.seen[a.actionId]||'未检查'}</span></button>`).join('');}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),2800);}
async function act(id,payload){if(busy)return;chosen=id;const slow=/commit$|\.exchange$|\.collect$|\.revive$|\.restart$|\.submit$|\.ack$|\.donate$|\.save$|\.accept$|\.reject$|_ad$|\.ad$|cancel_application$/.test(id);if(slow){busy=true;render();await new Promise(r=>setTimeout(r,420));}
 const result=engine.perform(id,payload===''?undefined:payload);busy=false;render();if(!result.ok||id.startsWith('rewards.claim.'))toast(result.detail);else if((!engine.s.modal&&slow)||['home.miner_pass.renew_ad','lending.pass.activate_ad','guild_apply.pass.activate_ad'].includes(id))toast(result.detail);
}
window.reviewAct=act;
screenShade.addEventListener('click',()=>{if(!busy&&!engine.s.modal)act('nav.back')});
let dismissPointer=null;
document.addEventListener('pointerdown',e=>{dismissPointer={x:e.clientX,y:e.clientY};},true);
document.addEventListener('click',e=>{
 if(busy||!e.target.closest('#phone')||e.target.closest('button,input,textarea,select,label,a,[data-action],[data-vip-page],[data-field]'))return;
 const root=e.target.closest('.modal')||(!engine.s.modal&&!['home','gameplay'].includes(engine.s.page)?e.target.closest('#game'):null);if(!root)return;
 if(dismissPointer&&Math.hypot(e.clientX-dismissPointer.x,e.clientY-dismissPointer.y)>12)return;
 for(let n=e.target;n&&n!==root;n=n.parentElement){const style=getComputedStyle(n);if(/auto|scroll/.test(style.overflowY+style.overflowX)&&(n.scrollHeight>n.clientHeight+1||n.scrollWidth>n.clientWidth+1))return;}
 e.stopPropagation();act(engine.s.modal==='reward'?(engine.s.rewardReturn==='home'?'gameplay.reward.dismiss':'warehouse_sell.reward.dismiss'):'nav.back');
},true);
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){act(a.dataset.action,a.dataset.payload);return;}if(e.target.matches('[data-dismiss]')&&!busy){act(engine.s.modal==='reward'?(engine.s.rewardReturn==='home'?'gameplay.reward.dismiss':'warehouse_sell.reward.dismiss'):'nav.back');return;}const route=e.target.closest('[data-route]');if(route&&!busy){const page=route.dataset.route;chosen=null;if(page==='sell'){engine.go('warehouse');engine.s.selectedItem=1;engine.perform('warehouse.item.sell');}else if(page==='gameplay'){engine.go('home');engine.open('levels');}else if(page==='lending'){engine.go(engine.s.debt?'debt':'lending');engine.s.amount=Math.min(100,engine.s.coins,engine.s.debt);}else if(['guild','shop'].includes(page)&&!engine.s.joined)engine.go('apply');else engine.go(page);render();return;}const p=e.target.closest('[data-prepare]');if(p&&!busy){chosen=p.dataset.prepare;engine.prepare(chosen);render();return;}const sc=e.target.closest('[data-scenario]');if(sc&&!busy){engine.scenario(sc.dataset.scenario);render();return;}});
let clickTimer;document.addEventListener('click',e=>{const tile=e.target.closest('[data-tile]');if(!tile||busy)return;clearTimeout(clickTimer);clickTimer=setTimeout(()=>act('gameplay.tile.flag',Number(tile.dataset.tile)),260);});
document.addEventListener('dblclick',e=>{const tile=e.target.closest('[data-tile]');if(!tile||busy)return;e.preventDefault();clearTimeout(clickTimer);tile.classList.add('digging');const i=Number(tile.dataset.tile);busy=true;setTimeout(()=>{busy=false;act('gameplay.tile.dig',i);},420);});
document.addEventListener('change',e=>{if(e.target.dataset.field)engine.s[e.target.dataset.field]=e.target.value;if(e.target.dataset.permission)engine.s.permissionDraft[e.target.dataset.permission]=e.target.checked;});
document.addEventListener('input',e=>{if(e.target.dataset.field)engine.s[e.target.dataset.field]=e.target.value;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!busy)act('nav.back');});
 $('back').onclick=()=>act(engine.s.page==='ranking'&&!engine.s.modal?'ranking.back':'nav.back');$('reset').onclick=()=>{if(!busy){engine.scenario('normal');chosen=null;render();}};
 $('ad-mode').onchange=e=>engine.s.adMode=e.target.value;$('tx-mode').onchange=e=>engine.s.txMode=e.target.value;$('action-system').onchange=actionList;
 $('home-status-fixture').onchange=e=>{if(!busy&&['home.debt.open','home.lending.open','home.loan.active','home.loan.matured','home.loan.runaway'].includes(e.target.value)){chosen=e.target.value;engine.prepare(chosen);render();}};
 $('action-system').innerHTML+=[...new Set(REVIEW_ACTIONS.map(a=>a.system))].map(s=>`<option>${s}</option>`).join('');
 $('scenarios').innerHTML=[['normal','默认状态'],['poor','金币不足'],['tired','旧体力为 0（不影响入场）'],['expired','VIP证过期'],['clearDebt','债务清零'],['unjoined','未加入协会'],['ordinary','普通成员'],['advance','推进 24 小时'],['aidReady','互助已送达'],['approved','申请获批准'],['win','开采成功'],['lose','开采失败'],['rich','资源充足'],['collection','全图鉴预览'],['emptyRank','榜单空态']].map(([id,t])=>`<button data-scenario="${id}">${t}</button>`).join('')+'<button id="safe">显示安全区</button>';
 $('safe').onclick=()=>{safe=!safe;render();};
 $('export').onclick=()=>{const a=document.createElement('a');const blob=new Blob([JSON.stringify({version:'5.0',kind:'人工评审操作记录，非自动验收',state:engine.s,events:engine.s.events},null,2)],{type:'application/json'});a.href=URL.createObjectURL(blob);a.download='鼹鼠挖矿-流程检查记录.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 function resize(){const w=Math.min(468,$('phone-wrap').parentElement.clientWidth);$('phone-wrap').style.width=w+'px';$('phone-wrap').style.height=w*1280/720+'px';$('phone').style.transform=`scale(${w/720})`;}
 const entry=new URLSearchParams(location.search).get('page');if(['guild','warehouse','shop'].includes(entry))engine.go(entry);const prepared=new URLSearchParams(location.search).get('action');if(prepared&&REVIEW_ACTIONS.some(a=>a.actionId===prepared)){chosen=prepared;engine.prepare(prepared);}if(new URLSearchParams(location.search).get('fixture')==='debt-concept'){engine.s.page='debt';engine.s.modal=null;engine.s.debtTotal=1000000;engine.s.debt=999500;engine.s.coins=2680;engine.s.amount=500;}if(new URLSearchParams(location.search).get('fixture')==='lending-concept'){const s=engine.s;s.page='lending';s.modal=null;s.debt=0;s.coins=85600;s.notes=[];s.loanEarned=12480;s.offers=[['安稳账房','mole_leader',8000,.02,6,'S',0],['老矿灯','mole_veteran',12000,.07,12,'B',.04],['深层测绘师','mole_explorer',30000,.24,24,'S',.03],['矿车修理匠','mole_engineer',10000,.10,6,'C',.01],['旧城承包人','mole_foreman',50000,.18,24,'A',.16]].map((o,id)=>({id,name:o[0],avatar:o[1],principal:o[2],rate:o[3],hours:o[4],credit:o[5],risk:o[6],signed:false,batch:s.batch}));}if(new URLSearchParams(location.search).get('fixture')==='notes-concept'){engine.s.page='notes';engine.s.modal=null;engine.s.coins=55600;engine.s.loanEarned=12480;engine.s.notes[0].due=11+42/60; }if(new URLSearchParams(location.search).get('fixture')==='guild-concept'){engine.s.page='apply';engine.s.joined=false;engine.s.application=false;engine.s.modal=null;engine.s.depth=650;}if(new URLSearchParams(location.search).get('fixture')==='shop-concept'){engine.s.page='shop';engine.s.modal=null;engine.s.coins=25634;engine.s.contribution=1280;}if(new URLSearchParams(location.search).get('fixture')==='aid-concept'){engine.s.page='aid';engine.s.modal=null;}setInterval(()=>{if(engine.s.page!=='aid'||!engine.aidSlots().some(r=>r.posted)||engine.s.modal||busy)return;engine.syncAid();const minute=engine.aidSlots().map((r,i)=>r.posted+':'+r.ready+':'+engine.aidRemaining(i)).join('|');if(engine.s.aidShownMinute!==minute){engine.s.aidShownMinute=minute;render();}},1000);if(new URLSearchParams(location.search).get('fixture')==='mine-concept'){engine.s.page='mine';engine.s.modal=null;}window.addEventListener('resize',resize);render();resize();
})();
