(()=>{
 const prior=window.productionUI;
 const time=seconds=>`${String(Math.floor(seconds/3600)).padStart(2,'0')}:${String(Math.floor(seconds%3600/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
 const face=(look,cls='')=>`<span class="beauty-face ${cls}" style="${look.art?'background-image:url(assets/visual/'+look.art+');background-size:100% 100%;background-position:center;':'--face-x:'+look.index%4*100/3+'%;--face-y:'+Math.floor(look.index/4)*100+'%'}" role="img" aria-label="${look.name}"></span>`;
 window.productionUI={...prior,modal(c){
  if(!['beauty','workshop'].includes(c.s.modal))return prior.modal(c);
  const {s,engine,img,num}=c,list=engine.beautyCatalog(),active=engine.beautyActive(),selected=list.find(x=>x.id===s.beautySelected)||list[0],wearing=active?.id===selected.id;
  const gear=engine.equipment(),revision=s.equipmentRevision||0;
  const top='';
  if(s.modal==='workshop'){const advance=s.workshopTab==='advance',names=['矿工十字镐','精钢十字镐','青铜战镐','黄金重镐','紫晶裂岩镐','星辉破界镐'],art=t=>'assets/visual/equipment-pickaxe'+(t?'-tier'+t:'')+'.svg',full=gear.enhance>=5,short=s.coins<gear.advanceCost||s.inventory[1]<gear.ironCost||s.inventory[2]<gear.copperCost;
   return `<div class="beauty-salon workshop-panel"><div class="tabs workshop-tabs" role="tablist"><button role="tab" aria-selected="${!advance}" class="game-btn ${advance?'secondary':'selected'}" data-action="workshop.tab" data-payload="upgrade">等级升级</button><button role="tab" aria-selected="${advance}" class="game-btn ${advance?'selected':'secondary'}" data-action="workshop.tab" data-payload="advance">强化升阶</button></div>${advance?'':`<div class="pickaxe-preview"><img src="${art(gear.enhance)}" alt="${names[gear.enhance]}"><h3>${names[gear.enhance]}</h3></div>`}
   ${advance?`<section class="workshop-detail"><div class="workshop-morph"><img src="${art(gear.enhance)}" alt="当前形态"><span>→</span><img src="${art(Math.min(5,gear.enhance+1))}" alt="升阶形态"></div><h3>${full?'已达最高阶':names[gear.enhance+1]}</h3><strong class="equipment-gain">深度加成 +${gear.enhance*25}%${full?'':' → +'+(gear.enhance+1)*25+'%'}</strong><p>${num(gear.maxDepth)}m${full?'':' → '+num(gear.nextAdvanceDepth)+'m'}</p>${full?'':`<div class="workshop-materials"><span title="铁矿石" class="${s.inventory[1]<gear.ironCost?'is-short':''}"><img src="assets/icons/ore_iron.png" alt="铁矿石"><b>${num(s.inventory[1])} / ${gear.ironCost}</b></span><span title="铜矿石" class="${s.inventory[2]<gear.copperCost?'is-short':''}"><img src="assets/icons/ore_copper.png" alt="铜矿石"><b>${num(s.inventory[2])} / ${gear.copperCost}</b></span></div><button class="game-btn" data-action="equipment.enhance.commit" data-payload="${revision}" ${short?'disabled':''}>${short?'金币或材料不足':'升阶'} · ${img('coin')} ${num(gear.advanceCost)}</button>`}</section>`:`<section class="workshop-detail"><h3>Lv.${num(gear.level)} → Lv.${num(gear.level+1)}</h3><strong class="equipment-gain">${num(gear.maxDepth)}m → ${num(gear.nextUpgradeDepth)}m</strong><button class="game-btn" data-action="equipment.upgrade.commit" data-payload="${revision}" ${s.coins<gear.upgradeCost?'disabled':''}>${s.coins<gear.upgradeCost?'金币不足':'升级'} · ${img('coin')} ${num(gear.upgradeCost)}</button></section>`}</div>`;
  }
  return `<div class="beauty-salon">${top}<div class="beauty-current"><span>当前：<b data-beauty-current>${active?active.name:'原貌'}</b></span><strong data-beauty-timer>${active?time(active.remaining):'未整容'}</strong></div><div class="beauty-grid">${list.map(look=>`<button type="button" class="beauty-choice ${look.id===selected.id?'is-selected':''}" data-action="beauty.select" data-payload="${look.id}" data-grade="${look.grade}" aria-label="${look.grade}级 ${look.name}" aria-pressed="${look.id===selected.id}">${face(look)}<b>${look.grade}</b><span>${look.name}</span></button>`).join('')}</div><section class="beauty-detail">${face(selected,'beauty-preview')}<div><h3>${selected.grade}级 · ${selected.name}</h3><p>有效期 <b>${selected.minutes} 分钟</b></p><p>C级及以上矿石权重 <b>+${Math.round(selected.boost*100)}%</b></p></div></section><p class="beauty-rule">仅影响已开放矿石；入场时锁定本轮概率。<br>最低掉落石头。到期恢复原貌。</p><p class="beauty-replace">立即替换当前外观，剩余时长不叠加。</p><button class="game-btn beauty-buy" data-action="beauty.buy.commit" data-payload="${selected.id}:${s.beautyRevision||0}" ${wearing||s.coins<selected.cost?'disabled':''}>${wearing?'已生效':s.coins<selected.cost?'金币不足':'整容'} ${img('coin')} ${num(selected.cost)}</button></div>`;
 }};
 window.BeautyUI={face,mount(){this.sync();document.querySelectorAll('.hc-interface [data-action]').forEach(el=>{const stage=review.featureStage(el.dataset.action),locked=review.buildingInfo().level<stage;el.classList.toggle('is-stage-locked',locked);el.querySelector('.feature-lock-hint')?.remove();if(locked){const hint=document.createElement('small');hint.className='feature-lock-hint';hint.textContent='第 '+stage+' 阶开放';el.append(hint);el.title=hint.textContent;}else el.removeAttribute('title');});},sync(){
  if(!window.review)return;window.WardrobeUI?.sync();const active=review.beautyActive();
  document.querySelectorAll('.hero-beauty-head').forEach(el=>{const index=active?.index??[7,0,3,4][HomePrison.expression(review.s)];el.hidden=false;el.parentElement.classList.toggle('has-beauty',!!active);el.style.setProperty('--face-x',index%4*100/3+'%');el.style.setProperty('--face-y',Math.floor(index/4)*100+'%');el.dataset.face=active?.id||'original';if(active?.art){el.style.backgroundImage=`url(assets/visual/${active.art})`;el.style.backgroundSize='100% 100%';el.style.backgroundPosition='center';}else{el.style.removeProperty('background-image');el.style.removeProperty('background-size');el.style.removeProperty('background-position');}});
  document.querySelectorAll('[data-charm]').forEach(el=>el.textContent=review.characterStats().charm);
  document.querySelectorAll('.hero-pickaxe').forEach(el=>{const tier=review.equipment().enhance;el.dataset.enhance=tier;el.style.backgroundImage='url(assets/visual/equipment-pickaxe'+(tier?'-tier'+tier:'')+'.svg)';});
  document.querySelectorAll('[data-beauty-timer]').forEach(el=>el.textContent=active?time(active.remaining):'已到期 · 恢复原貌');
  document.querySelectorAll('[data-beauty-current]').forEach(el=>el.textContent=active?active.name:'原貌');
  window.HomePrison?.syncSpeech?.();
  if(review.s.modal==='beauty'){const btn=document.querySelector('.beauty-buy'),selected=review.beautyCatalog().find(x=>x.id===review.s.beautySelected);if(btn&&selected&&active?.id!==selected.id&&review.s.coins>=selected.cost){btn.disabled=false;if(btn.textContent.includes('已生效'))btn.innerHTML=`整容 <img class="icon" src="assets/icons/coin.png" alt="金币"> ${selected.cost.toLocaleString('zh-CN')}`;}}
 }};
 setInterval(()=>{if(!document.hidden)BeautyUI.sync();},1000);
})();
