/* One main building evolves along a fixed, sequential upgrade path. */
(()=>{
 const prior=window.productionUI;
 window.productionUI={...prior,modal(c){
  if(c.s.modal!=='buildingUpgrade')return prior.modal(c);
  const {s,engine,img,num,esc}=c,current=engine.buildingInfo(),growth=engine.buildingGrowth(),tiers=engine.buildings(),next=tiers.find(t=>t.level===current.level+1),ready=growth.rank===growth.max,materials=next?engine.buildingMaterials(next.level):[];
  const feature=['基础功能','排行榜','美容院','衣橱','矿工协会','宝石交易所'],browse=s.buildingBrowse||current.level;
  const icons=['assets/visual/equipment-pickaxe.svg','assets/icons/trophy.png','assets/visual/beauty-icon-v2.png','assets/visual/wardrobe-icon-v2.png','assets/icons/guild_shield.png','assets/visual/gem-exchange-icon-v2.png'];
  const reward=(stage,owned=false)=>`<section class="building-unlock-card"><img src="${icons[stage-1]}" alt=""><span class="building-unlock-copy"><small>${owned?'已解锁':'第 '+stage+' 阶解锁'}</small><strong>${feature[stage-1]}</strong><span>${['家园 · 账房 · 工坊 · VIP证','查看排名','更换脸部造型','永久服装 · 安全帽','加入矿工协会','交易功能开发中'][stage-1]}</span></span></section>`;
  const art=t=>`<span class="building-evolution-art"><span class="residence-building" style="--house-x:${(t.level-1)%3*50}%;--house-y:${Math.floor((t.level-1)/3)*100}%"></span></span>`;
  const enough=next&&materials.every(m=>m.owned>=m.amount)&&s.coins>=next.cost;
  return `<div class="building-evolution">
   <div class="building-path" aria-label="建筑线性进阶路线">${tiers.map(t=>`<button type="button" data-action="building.stage.select" data-payload="${t.level}" class="${t.level===browse?'is-current':t.level<current.level?'is-complete':''}"><i>${t.level}</i><span class="building-path-icon ${t.level>current.level?'is-locked':''}">${'<img src="'+icons[t.level-1]+'" alt="">'}</span><small>${feature[t.level-1]}</small></button>`).join('')}</div>
   ${browse!==current.level?`<div class="building-stage-preview">${art(tiers[browse-1])}<h3>${esc(HomePrison.residenceNames[browse-1])}</h3><p>第 ${browse} 阶 · ${browse<current.level?'已完成进阶':'尚未进阶'}</p>${reward(browse,browse<=current.level)}<button class="game-btn" data-action="building.stage.select" data-payload="${current.level}">返回当前建筑</button></div>`:`<div class="building-evolution-pair"><div class="building-main"><small>当前 · ${current.level} 阶</small>${art(current)}<h3>${esc(HomePrison.residenceNames[current.level-1])}</h3></div>${next?`<span class="building-evolution-arrow">→</span><div class="building-future"><small>进阶后 · ${next.level} 阶</small>${art(next)}<h3>${esc(HomePrison.residenceNames[next.level-1])}</h3></div>`:''}</div>
   ${next?reward(next.level):''}
   ${!ready?`<div class="building-rank"><div><b>主建筑等级</b><strong>Lv.${growth.rank} / ${growth.max}</strong></div><div class="building-rank-segments" role="progressbar" aria-label="建筑等级进度" aria-valuenow="${growth.rank}" aria-valuemin="0" aria-valuemax="${growth.max}">${Array.from({length:growth.max},(_,i)=>`<span class="${i<growth.rank?'is-filled':''}" aria-hidden="true"></span>`).join('')}</div></div><button class="game-btn building-upgrade-button" data-action="building.rank.commit" data-payload="${current.level}:${growth.rank}" ${s.coins<growth.cost?'disabled':''}><span>${s.coins<growth.cost?'金币不足':'升级 · Lv.'+(growth.rank+1)}</span><span class="building-upgrade-cost">${img('coin')} ${num(growth.cost)}</span></button>`:next?`<div class="building-materials"><span>进阶材料</span>${materials.map(m=>`<div class="${m.owned<m.amount?'is-short':''}">${img(m.icon)}<span>${esc(m.name)}</span><b>${num(m.owned)} / ${num(m.amount)}</b></div>`).join('')}</div><button class="game-btn building-upgrade-button" data-action="building.upgrade.commit" data-payload="${next.level}" ${enough?'':'disabled'}><span>${enough?'进阶为'+esc(HomePrison.residenceNames[next.level-1]):'进阶资源不足'}</span><span class="building-upgrade-cost">${img('coin')} ${num(next.cost)}</span></button>`:'<div class="building-evolution-note">已拥有 · 最终建筑</div>'}
  `}</div>`;
 }};
 window.BuildingUpgrade={mount(s){if(s.modal!=='buildingUpgrade')return;const el=document.querySelector('.building-evolution');if(!el)return;let x;el.addEventListener('pointerdown',e=>{x=e.clientX});el.addEventListener('pointerup',e=>{if(x==null||Math.abs(e.clientX-x)<50)return;const n=Math.max(1,Math.min(6,(s.buildingBrowse||s.buildingLevel)+(e.clientX<x?1:-1)));x=null;reviewAct('building.stage.select',String(n));});}};
})();
