/* Concept-specific composition, reusing the existing atomic interaction engine. */
(()=>{
const previous=window.productionUI;
const references={home:'home',gameplay:'gameplay',ranking:'ranking',debt:'debt',lending:'lending',notes:'notes',guild:'guild',members:'member',manage:'member',audit:'apply',apply:'apply',aid:'aid',mine:'mine',shop:'shop',warehouse:'warehouse'};
window.productionUI={...previous,
 hud(c){if(c.s.page==='apply')return '';return previous.hud(c);},
 compare(s){const key=s.modal==='pass'?'pass':['loan','note','debtCleared','repay','repaid'].includes(s.modal)?'loan-dialogs':s.modal==='member'||s.modal==='kick'||s.modal==='role'?'member':references[s.page];const box=document.getElementById('concept-compare');box.hidden=!key;if(key){document.getElementById('concept-image').src='references/'+key+'.png';document.getElementById('concept-note').textContent='对应概念原稿。功能页与子弹窗统一提供右上角关闭按钮；保留无试玩、无协会建设，数值来自可操作状态，不照抄图片。';}},
 screen(c){const {s,engine,img,btn,num,esc}=c;
 if(s.page==='apply')return `<div class="apply-status">${s.joined?'已加入协会':s.application?'申请审核中':'尚未加入'}</div><section class="apply-reception" role="img" aria-label="鼹鼠在协会接待处填写申请"><div class="apply-board">${img('guild_shield','')}<strong>${esc(s.guildName)}</strong><small>Lv.3</small></div></section><section class="apply-conditions"><h3>入会申请条件</h3><div>${img('loan_contract')}<span>VIP证</span><b class="${engine.pass()?'good':'bad'}">${engine.pass()?'有效':'已过期'}</b></div><div>${img('shovel_energy')}<span>最深完成</span><b>${num(s.depth)} 米</b></div></section><div class="scroll apply-candidates">${[s.guildName,'深层勘探团'].map((name,i)=>`<button class="apply-candidate" data-action="guild_apply.guild.select" data-payload="${i}">${img('guild_shield','avatar')}<div><strong>${esc(name)}</strong><small>${i?'1,000':'100'} 米门槛 · ${i?'28':'18'}/30 人</small></div><span>${s.depth<(i?1000:100)?'深度不足':'查看申请'}</span></button>`).join('')}</div>${s.application?btn('撤回申请','guild_apply.cancel_application','','secondary'):btn('创建协会','guild_apply.create.open')}`;
 if(s.page==='ranking'){
 const value=i=>s.rank==='wealth'?num(999999-i*32100):num(8000-i*300)+'米';
 return `<div class="tabs ranking-tabs">${btn(img('trophy')+' 财富榜','ranking.tab.wealth','',s.rank==='wealth'?'selected':'secondary')}${btn(img('shovel_energy')+' 深度榜','ranking.tab.depth','',s.rank==='depth'?'selected':'secondary')}</div><button class="rank-rules" data-action="ranking.rules.open">排名规则 · 前 100 名</button>${s.emptyRank?'<div class="paper empty grow">暂无排名</div>':`<div class="podium">${[1,0,2].map(i=>`<div class="podium-place place-${i}"><div class="medal"><img src="assets/visual/rank-${['gold','silver','bronze'][i]}.png" alt=""><b>${i+1}</b></div><section><strong>${['老矿灯','铜轮队长','岩仔'][i]}</strong><b>${value(i)}</b></section></div>`).join('')}</div><div class="rank-head"><span>名次</span><span>矿工</span><span>${s.rank==='wealth'?'财富值':'挖掘深度'}</span></div><div class="scroll ranking-list">${Array.from({length:13},(_,j)=>{const i=j+3;return `<div class="rank-entry"><b>${i+1}</b><span>${['阿铜','老矿灯','岩仔','铜轮队长'][i%4]}${i>=4?' '+(i+1):''}</span><strong>${value(i)}</strong></div>`;}).join('')}</div>`}<div class="self-rank"><span>我的排名<b>${s.emptyRank?'10,000+':'128'}</b></span><strong>你</strong><span>${s.rank==='wealth'?'财富值':'挖掘深度'}<b>${s.rank==='wealth'?num(s.coins-s.debt):s.depth+'米'}</b></span></div>`;
 }
 if(s.page==='lending')return `<div class="loan-summary"><div>${img('coin')}<span>可用金币<b>${num(s.coins)}</b></span></div><div>${img('loan_contract')}<span>借据<b>${engine.activeNotes().length}/${engine.slots()}</b></span></div></div><div class="tabs">${btn('放贷大厅','lending.tab.hall','','selected')}${btn('我的借据','lending.tab.notes','','secondary')}</div><div class="loan-refresh"><span>距更新 <b>${Math.max(0,s.refreshAt-s.clock)} 小时</b></span>${btn('广告刷新','lending.refresh.ad','','small')}</div><div class="scroll stack slots loan-offers">${s.offers.map(o=>`<button class="note paper" data-action="${o.signed?'lending.candidate.loaned':'lending.candidate.select'}" data-payload="${o.id}">${img(o.avatar,'avatar','avatars')}<div class="offer-body"><strong>${o.name}</strong><div class="offer-stats"><span>本金<b>${num(o.principal)}</b></span><span>期限<b>${o.hours}小时</b></span><span>利率<b class="good">${Math.round(o.rate*100)}%</b></span></div>${o.signed?'<small>已放贷</small>':''}</div></button>`).join('')}</div>`;
 if(s.page==='guild')return `<section class="guild-identity">${img('guild_shield','')}<div><h3>${esc(s.guildName)} <small>Lv.3</small></h3><p>${esc(s.notice)}</p></div></section><div class="guild-stats"><span>成员 ${s.members.length}/30</span><button class="pass-state ${engine.pass()?'':'expired'}" data-action="home.miner_pass">VIP证 · ${engine.pass()?'有效':'过期'}</button></div><section class="compact-members"><div>${s.members.slice(0,3).map(m=>img(m.avatar,'avatar','avatars')).join('')}</div>${btn('成员名单','guild.members.open','','secondary')}${s.president?btn('协会管理','guild.manage.open','','secondary'):''}</section><div class="guild-modules">${[['ore_iron','物资互助','申请与捐赠','aid'],['treasure_chest','联合开采','自动开采矿石','mine'],['shop','协会商店','贡献兑换商品','shop']].map(([icon,t,sub,id])=>`<button data-action="guild.module.${id}" class="module-card"><b>${t}</b>${img(icon,'')}<span>${sub}</span></button>`).join('')}</div>`;
 if(s.page==='debt')return `<section class="debt-overview"><span>可用金币<b>${num(s.coins)}</b></span><span>剩余债务<b class="bad">${num(s.debt)}</b></span></section><section class="debt-goal">${img('loan_contract','')}<div><small>最终目标</small><h3>还清全部债务</h3><p>持有效VIP证 · 解锁放贷</p></div></section><section class="debt-illustration">${img('mole_explorer','debt-mole','avatars')}<div>${img('coin','')}<strong>${s.debt===0?'债务已还清':'还款后剩余'}</strong><b>${num(Math.max(0,s.debt-s.amount))}</b></div></section><section class="debt-controls"><h3>还款金额</h3><div class="quantity">${btn('−','debt.amount.minus','','small',s.amount<=100)}<output>${num(s.amount)}</output>${btn('+','debt.amount.plus','','small',s.amount>=Math.min(s.coins,s.debt))}${btn('最大','debt.amount.max','','small',!s.debt)}</div><p>剩余金币 <b>${num(s.coins-s.amount)}</b></p></section>${btn(s.debt===0?'进入放贷':'偿还 '+num(s.amount)+' 金币',s.debt===0?'home.lending.open':'debt.repay.open','','',s.debt>0&&s.amount<=0)}`;
 if(s.page==='gameplay'){const html=previous.screen(c);if(html!==undefined)return html;return `<div class="play-top"><b>第 ${s.level} 关</b><b>${img('treasure_chest')} ${engine.found()}/${s.n}</b></div>${btn(img('shovel_energy')+' × '+s.shovels,'gameplay.energy.info','','secondary')}<p class="play-instruction">单击插旗 · 双击挖掘</p><div class="board-coordinates"><div class="column-coordinates">${Array.from({length:s.n},(_,i)=>`<span>${i+1}</span>`).join('')}</div><div class="row-coordinates">${Array.from({length:s.n},(_,i)=>`<span>${String.fromCharCode(65+i)}</span>`).join('')}</div><div class="board" style="--n:${s.n}">${Array.from({length:s.n*s.n},(_,i)=>`<button class="tile ${s.dug.includes(i)?'dug':''} ${s.flags.includes(i)?'flagged':''} ${s.hint===i?'hint':''}" data-tile="${i}" aria-label="第 ${Math.floor(i/s.n)+1} 行第 ${i%s.n+1} 列${s.dug.includes(i)?'已挖掘':''}">${s.dug.includes(i)&&engine.treasures().includes(i)?img(engine.treasureItem(i)[0],''):''}</button>`).join('')}</div></div><div class="grow"></div>${btn(img('radar_ad')+' 雷达指南 · 广告','gameplay.radar.watch_ad')}`;}
 return previous.screen(c);
 },
 modal(c){const {s,engine,img,btn,num,esc}=c;const {ITEMS,GOODS}=MoleReview;
 if(s.modal==='pass'){
 const valid=engine.pass(),chosen=c.chosen;const id=chosen?.includes('lending.pass')?'lending.pass.activate_ad':chosen?.includes('guild_apply.pass')?'guild_apply.pass.activate_ad':'home.miner_pass.renew_ad';
 const days=s.passStamps>=7||s.passStamps===6&&(s.passStampDay!==Math.floor(s.clock/24)||(s.passStampsToday||0)<2)?30:3;
 return `<div class="license-card license-concept"><div class="license-live"><strong>${s.passStamps>=7?'30 天VIP证':'矿工通行证'}</strong><b class="license-stamp ${valid?'':'expired'}">${valid?'已激活':'已过期'}</b><small>${valid?'剩余 '+Math.ceil(s.passUntil-s.clock)+' 小时':'持证权益已暂停'}</small><div class="actions">${btn('观看广告 · '+(valid?'续期':'补领')+' '+days+' 天',id)}</div></div></div><section class="license-progress"><div><b>累计 ${s.passStamps||0}/7</b><small>${s.passStamps>=7?'已升级 30 天VIP证':'集满 7 次升级 30 天VIP证'}</small></div><div class="stamp-track">${Array.from({length:7},(_,i)=>`<span class="${i<(s.passStamps||0)?'stamped':''}">${img('shovel_energy','')}</span>`).join('')}</div><p>每日最多计入 2 次</p></section><h3 class="rights-title">持证权益</h3><div class="license-rights">${[['guild_shield','进入矿工协会','加入协会，享受矿工权益'],['ore_iron','物资互助','申请与捐赠矿石'],['treasure_chest','联合开采','定时领取矿石'],['shop','协会商店','贡献兑换商品'],['loan_contract','解锁放贷业务','还清债务后开启']].map(([icon,t,sub],i)=>{const enabled=valid&&(i!==4||s.debt===0);return `<div>${img(icon,'')}<section><b>${t}</b><small>${sub}</small></section><span class="${enabled?'good':'bad'}">${enabled?'已生效':valid?'待还清':'已暂停'}</span></div>`;}).join('')}</div>`;
 }
 const hero=(icon,title,subtitle='',folder='icons')=>`<div class="dialog-hero">${img(icon,'dialog-art',folder)}<div><h3>${esc(title)}</h3>${subtitle?`<p>${subtitle}</p>`:''}</div></div>`;
 const stat=(icon,label,value,cls='')=>`<div class="detail-stat">${img(icon)}<span>${label}</span><strong class="${cls}">${value}</strong></div>`;
 const actions=html=>`<div class="actions">${html}</div>`;
 const qty=(prefix,max,step=1)=>`<div class="quantity">${btn('−',prefix+'.minus','','small',s.amount<=step)}<output>${num(s.amount)}</output>${btn('+',prefix+'.plus','','small',s.amount>=max)}${step===1?btn('最大',prefix+'.max','','small',!max):''}</div>`;
 const info=(icon,eyebrow,title,copy)=>`<section class="dialog-info"><span class="dialog-info-icon">${img(icon,'')}</span><div><small>${eyebrow}</small><h3>${title}</h3><p>${copy}</p></div></section>`;
 if(s.modal==='rankingRules')return info('trophy','排行榜规则','公平记录每一次深入','财富榜按净财富排序，深度榜按最深挖掘记录排序。')+`<div class="dialog-rule-list"><p><b>01</b><span>榜单展示前 100 名矿工</span></p><p><b>02</b><span>本人名次始终固定显示</span></p><p><b>03</b><span>榜外统一显示 10,000+</span></p></div>`;
 if(s.modal==='energy')return info('shovel_energy','铲子能量','合理规划每一次挖掘','挖掘会消耗铲子，插旗与重复点击不会消耗。')+`<div class="detail-group">${stat('warehouse','计算规则','单边格数 + 3')}${stat('shovel_energy','本局初始',s.n+3+' 把')}${stat('shovel_energy','当前剩余',s.shovels+' 把',s.shovels>0?'good':'bad')}</div>`;
 if(s.modal==='tutorial'){const flag=s.tutorial===1;return info(flag?'red_flag':'shovel_energy',`教学步骤 ${flag?'1':'2'} / 2`,flag?'先标记可疑位置':'确认后开始挖掘',flag?'单击格子插旗，记录你的判断；再次单击可以取消。':'双击目标格子进行挖掘，每次会消耗 1 把铲子。')+actions(btn(flag?'下一步':'开始挖掘','gameplay.tutorial.next'));}
 if(s.modal==='lockedLevel')return info('lock','矿层尚未开放','继续积累财富等级','财富等级达到 Lv.9 后，即可进入更深的矿层。')+`<div class="detail-group">${stat('trophy','当前财富等级','Lv.'+s.wealth)}${stat('lock','解锁要求','Lv.9',s.wealth>=9?'good':'')}</div>`;
 if(s.modal==='slotLocked')return info('lock','借据槽位','新的放贷席位尚未开放','提升财富等级，逐步扩充可同时持有的借据数量。')+`<div class="detail-group">${stat('trophy','解锁要求','财富 Lv.11')}${stat('loan_contract','解锁内容','第 5 个借据槽位')}</div>`;
 if(s.modal==='wealth')return info('trophy','财富档案','矿工成长概览','金币、债务和挖掘深度共同记录你的经营进度。')+`<div class="detail-group">${stat('trophy','财富等级','Lv.'+s.wealth)}${stat('coin','当前金币',num(s.coins))}${stat('loan_contract','剩余债务',num(s.debt),s.debt?'bad':'good')}${stat('shovel_energy','最大深度',num(s.depth)+' 米')}</div>`;
 if(s.modal==='applied')return info('guild_shield','申请已提交','等待协会审核','申请结果会在协会入口同步更新，审核期间可以随时撤回。')+actions(btn('撤回申请','guild_apply.cancel_application','','secondary'));
 if(s.modal==='createGuild')return info('guild_shield','创建矿工协会','建立自己的矿工团队','设置协会名称后支付创建费用，即可成为协会会长。')+`<label class="dialog-field"><span>协会名称</span><input class="game-input" data-field="guildDraft" maxlength="12" value="${esc(s.guildDraft)}"><small>最多 12 个字符</small></label><div class="detail-group">${stat('coin','创建费用','10,000 金币')}${stat('guild_shield','创建后职务','协会会长')}</div>`+actions(btn('支付 10,000 金币创建','guild_apply.create.commit'));
 if(s.modal==='role')return info('guild_shield','成员权限','配置成员职责','职务决定成员可以使用的协会管理功能。')+`<label class="dialog-field"><span>职务</span><select class="game-input" data-field="roleDraft">${['成员','管理员','副会长'].map(v=>`<option ${s.roleDraft===v?'selected':''}>${v}</option>`).join('')}</select></label><div class="permission-grid">${[['audit','审核申请'],['notice','编辑公告'],['aid','处理互助'],['kick','移出普通成员']].map(([key,label])=>`<label class="check-row"><input type="checkbox" data-permission="${key}" ${s.permissionDraft?.[key]?'checked':''}><span>${label}</span></label>`).join('')}</div>`+actions(btn('保存权限','guild.member.role.commit'));
 if(s.modal==='levels')return `<div class="level-pager">${btn('上一关','gameplay.level.previous','','secondary')}<b>第 ${s.level} 关</b>${btn('下一关','gameplay.level.next')}</div><div class="level-art"><img src="assets/visual/mine-operation.png" alt="矿层场景"></div><div class="detail-group">${stat('warehouse','棋盘',s.n+' × '+s.n)}${stat('treasure_chest','宝藏',s.n+' 个')}${stat('shovel_energy','铲子能量',(s.n+3)+' 次')}${stat('trophy','财富等级','Lv.'+s.wealth)}</div>${actions(btn('未解锁矿层','gameplay.level.locked','','secondary'))}${actions(btn(img('coin')+' 支付 '+num(engine.levelInfo().coinCost)+' 金币进入','gameplay.level.enter','','',s.coins<engine.levelInfo().coinCost))}`;
 if(['item','source','sell'].includes(s.modal)){const it=ITEMS[s.selectedItem];return hero(it[0],it[1],`<span class="quality-chip">${it[2]} 品质</span>`)+`<div class="detail-group">${stat('shovel_energy','出现深度',it[4]+' 米')}${s.modal!=='source'?stat('warehouse','拥有',num(s.inventory[s.selectedItem])):''}${s.modal==='sell'?stat('coin','单价',num(it[3])):''}</div>`+(s.modal==='source'?'<p class="dialog-caption">前往对应矿层挖掘发现</p>':s.modal==='item'?actions(btn('出售','warehouse.item.sell')):qty('warehouse_sell.amount',s.inventory[s.selectedItem])+`<div class="dialog-total">预计获得 ${img('coin')}<b>${num(s.amount*it[3])}</b></div>`+actions(btn('出售','warehouse_sell.commit')));}
 if(s.modal==='exchange'){const g=GOODS[s.selectedGood];return hero(g[0],g[1])+`<div class="detail-group">${stat('guild_shield','花费贡献',num(g[2]))}${stat('guild_shield','可用贡献',num(s.contribution))}${stat('shop','剩余限购',s.stock[s.selectedGood])}</div>`+actions(btn('兑换','guild_shop.item.exchange'));}
 if(s.modal==='contribute')return hero('coin','金币贡献','100 金币 → 10 贡献')+stat('coin','可用金币',num(s.coins))+qty('guild_shop.contribute',s.coins,100)+`<div class="dialog-total">获得贡献 ${img('guild_shield')}<b>${num(Math.floor(s.amount/10))}</b></div>`+actions(btn('贡献金币','guild_shop.contribute.commit'));
 if(s.modal==='loan'){const o=s.offers[s.selectedOffer];return hero(o.avatar,o.name,'借款合同','avatars')+`<div class="detail-group">${stat('coin','本金',num(o.principal))}${stat('loan_contract','期限',o.hours+' 小时')}${stat('coin','利率',Math.round(o.rate*100)+'%')}${stat('coin','预计利息',num(Math.round(o.principal*o.rate)),'good')}</div><div class="dialog-total">到期应收 <b>${num(Math.round(o.principal*(1+o.rate)))}</b></div><p class="dialog-caption bad">借款人可能跑路，损失本金</p>`+actions(btn('签署借据并放贷','lending.loan.commit'));}
 if(s.modal==='note'){const n=engine.note();if(!n)return;return hero(n.avatar,n.name,n.status==='active'?'还款中':n.status==='matured'?'<span class="good">已到期</span>':'<span class="bad">借款人跑路</span>','avatars')+`<div class="detail-group">${stat('coin','本金',num(n.principal))}${stat('coin','利息',num(n.interest),'good')}${n.status==='active'?stat('loan_contract','剩余',Math.max(0,n.due-s.clock)+' 小时'):''}</div>`+(n.status==='matured'?`<div class="dialog-total">本息合计 <b>${num(n.principal+n.interest)}</b></div>`+actions(btn('领取本息','lending.note.collect')):n.status==='runaway'?`<div class="dialog-total bad">本金损失 <b>${num(n.principal)}</b></div>`+actions(btn('确认损失','lending.note.runaway.ack','','danger')):'');}
 if(s.modal==='member'||s.modal==='kick'){const m=engine.member();if(!m)return;return hero(m.avatar,m.name,`<span class="quality-chip">${m.role}</span>`,'avatars')+`<div class="detail-group">${stat('loan_contract','VIP证',m.expired?'已过期':'有效',m.expired?'bad':'good')}${stat('guild_shield','所在协会',esc(s.guildName))}</div>`+(s.modal==='kick'?'<p class="dialog-caption">移出后需重新申请加入</p>'+actions(btn('取消','nav.back','','secondary')+btn('移出成员','guild.member.kick.commit','','danger')):s.president&&m.id!==0?actions(btn('调整职务','guild.member.role.open','','secondary')+btn('移出协会','guild.member.kick.open','','danger')):'');}
 if(s.modal==='repay')return hero('loan_contract','偿还债务')+`<div class="detail-group">${stat('coin','本次偿还',num(s.snapshot?.amount))}${stat('coin','偿还后债务',num(s.debt-(s.snapshot?.amount||0)),'good')}</div>`+actions(btn('偿还','debt.repay.commit'));
 if(s.modal==='success'||s.modal==='failed')return hero(s.modal==='success'?'treasure_chest':'shovel_energy',s.modal==='success'?'全部宝藏已发现':'本轮铲子已用完',s.modal==='success'?`${s.n} 个宝藏`:`剩余 ${s.n-engine.found()} 个宝藏`)+(s.modal==='success'?actions(btn('领取全部','gameplay.success.collect')):actions(btn('复活 +2 铲 · 广告','gameplay.fail.revive'))+actions(btn('重开 · '+num(engine.levelInfo().coinCost)+' 金币','gameplay.fail.restart','','secondary',s.coins<engine.levelInfo().coinCost)));
 return previous.modal(c);
 }
};
})();
