/* Reuse the guild shell, shared panel/button skins and debt contract icon. */
(()=>{const portrait=(o,cls='credit-avatar')=>HomeBorrowers.portrait(o,cls+' credit-miner borrower-portrait');const prev=window.productionUI;window.productionUI={...prev,
screen(c){if(c.s.page!=='lending')return prev.screen(c);const {s,engine,img,btn,num,esc}=c,o=s.offers[s.selectedOffer]||s.offers[0];
const percent=x=>x==null?'—':Number((x*100).toFixed(2))+'%';
const earned=(s.loanEarned||0)+s.history.filter(n=>n.status==='collected').reduce((sum,n)=>sum+(n.interest||0),0);
return `<div class="credit-hall"><div class="credit-stats"><div>${img('coin')}<section><span>可用金币</span><b>${num(s.coins)}</b></section></div><div><img class="icon" src="assets/visual/debt-contract.png" alt="借据"><section><span>借据</span><b>${engine.activeNotes().length}/${engine.slots()}</b></section></div><div>${img('coin')}<section><span>累计利息</span><b>${num(earned)}</b></section></div></div>
<div class="credit-tabs">${btn('放贷大厅','lending.tab.hall','','selected')}${btn('我的借据','lending.tab.notes','','secondary')}</div>
<div class="credit-refresh"><span>VIP利息加成 +${Math.round(engine.loanVipBoost()*100)}%</span><b>距更新 ${Math.max(0,s.refreshAt-s.clock)}小时</b>${btn('▷ 广告刷新','lending.refresh.ad','','small')}</div>
<div class="scroll credit-offers">${s.offers.map(x=>`<button class="credit-offer ${x.id===s.selectedOffer?'chosen':''}" data-action="${x.signed?'lending.candidate.loaned':'lending.candidate.focus'}" data-payload="${x.id}" aria-pressed="${x.id===s.selectedOffer}">${portrait(x)}<div class="credit-name"><strong>${esc(x.name)}</strong><b class="credit-grade grade-${x.credit||'none'}">${x.credit?x.credit+'级信用':'信用 —'}${x.signed?' · 已放贷':''}</b></div><div class="credit-number"><small>本金</small><b>${num(x.principal)}</b></div><div class="credit-number"><small>期限</small><b>${x.hours}小时</b></div><div class="credit-number"><small>利率</small><b>${percent(x.rate)}</b></div><div class="credit-number"><small>风险</small><b class="${x.risk>0.03?'high-risk':'low-risk'}">${percent(x.risk)}</b></div></button>`).join('')}</div>
<div class="credit-selection"><section><span>当前选择</span><b>${esc(o.name)}</b></section><section><span>到期应收（含加成）</span><b>${num(o.principal+(o.interest??engine.loanInterest(o)))}</b></section><section><span>本金全损风险</span><b>${percent(o.risk)}</b></section></div>
<div class="credit-confirm">${btn(o.signed?'查看借据':'确认放贷',o.signed?'lending.candidate.loaned':'lending.candidate.select',o.id)}</div></div>`;
},modal(c){if(c.s.modal!=='loan')return prev.modal(c);const {s,engine,img,btn,num,esc}=c,o=s.snapshot||s.offers[s.selectedOffer];return `<div class="credit-loan-hero">${portrait(o,'credit-loan-avatar')}<div><strong>${esc(o.name)}</strong><span>${o.credit?o.credit+'级信用':'借款合同'}</span></div></div><div class="debt-dialog-summary"><div><span>放贷本金</span><b>${num(o.principal)}</b></div><div><span>期限 / 利率</span><b>${o.hours}小时 / ${Number((o.rate*100).toFixed(2))}%</b></div><div><span>到期应收</span><b>${num(o.principal+(o.interest??engine.loanInterest(o)))}</b></div>${o.risk!=null?`<div><span>本金全损风险</span><b>${Number((o.risk*100).toFixed(2))}%</b></div>`:''}</div><p class="good">VIP利息 +${Math.round((o.vipBoost??engine.loanVipBoost())*100)}% · 签约锁定</p><div class="actions">${btn('放贷 '+num(o.principal)+' 金币','lending.loan.commit')}</div>`;}
};})();
