/* Shares the loan hall shell, statistics, tabs and portrait atlas. */
(()=>{const prev=window.productionUI;
const portrait=n=>HomeBorrowers.portrait(n,'credit-miner note-miner borrower-portrait');
window.productionUI={...prev,screen(c){if(c.s.page!=='notes')return prev.screen(c);const {s,engine,btn,num,esc}=c;
const shared=prev.screen({...c,s:{...s,page:'lending'}}).split('<div class="credit-refresh">')[0].replace('credit-hall','credit-hall credit-notes');
const list=engine.activeNotes();
return shared+`<div class="credit-note-list">${Array.from({length:6},(_,i)=>{const n=list[i],locked=i>=engine.slots();if(!n)return `<button class="credit-note empty-note ${locked?'note-locked':''}" data-action="lending.slot.${locked?'locked':'empty'}"><b class="note-index">${i+1}</b>${locked?'<span class="note-lock">🔒</span>':''}<span>${locked?'未解锁':'空闲借据槽位'}${locked?'<small>财富 Lv.11 解锁</small>':''}</span></button>`;
const active=n.status==='active',ready=n.status==='matured',action=active?'lending.note.active.open':ready?'lending.note.collect':'lending.note.runaway.ack';
const seconds=Math.round(Math.max(0,n.due-s.clock)*3600),time=String(Math.floor(seconds/3600)).padStart(2,'0')+':'+String(Math.floor(seconds/60)%60).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');
const field=(label,value)=>`<div class="credit-number"><small>${label}</small><b>${value}</b></div>`;
return `<div class="credit-note filled-note">${portrait(n)}<div class="credit-name"><strong>${esc(n.name)}</strong><span class="note-status ${ready?'ready':!active?'lost':''}">${active?'进行中':ready?'待领取':'借款人跑路'}</span></div>${field('本金',num(n.principal))}${active?field('利率',Math.round(n.interest/n.principal*100)+'%')+field('剩余',time)+field('到期应收',num(n.principal+n.interest)):field('利息',num(n.interest))+field(ready?'本息合计':'本金损失',num(n.principal+(ready?n.interest:0)))+`<div class="credit-number note-action">${btn(ready?'领取':'确认',action,n.id,'note-claim')}</div>`}${active?`<button class="note-inspect" data-action="${action}" data-payload="${n.id}" aria-label="查看${esc(n.name)}借据"></button>`:''}</div>`;}).join('')}</div></div>`;
},modal(c){if(c.s.modal!=='note')return prev.modal(c);const n=c.engine.note();if(!n)return prev.modal(c);const {num,btn,esc,s}=c;return `<div class="credit-loan-hero">${portrait(n)}<strong>${esc(n.name)}</strong></div><div class="debt-dialog-summary"><div><span>本金</span><b>${num(n.principal)}</b></div><div><span>利息</span><b>${num(n.interest)}</b></div><div><span>${n.status==='active'?'剩余时间':n.status==='matured'?'本息合计':'本金损失'}</span><b>${n.status==='active'?Math.max(0,n.due-s.clock)+' 小时':num(n.principal+(n.status==='matured'?n.interest:0))}</b></div></div>${n.status==='active'?'':`<div class="actions">${btn(n.status==='matured'?'领取本息':'确认损失',n.status==='matured'?'lending.note.collect':'lending.note.runaway.ack')}</div>`}`;}};})();
