/* Reusable illustration + live content. No full-screen concept art is used as a button surface. */
window.productionUI={
 hud({s,img,num}){if(s.page==='warehouse')return '';if(s.page==='shop')return `<div class="hud shop-hud"><div>${img('coin')} ${num(s.coins)}</div><div>${img('guild_shield')} ${num(s.contribution)}</div><div>协会 Lv.3</div></div>`;},
 compare(s){const key=s.modal==='pass'?'pass':s.page==='warehouse'?'warehouse':['guild','shop','aid','mine','members','manage','apply','audit'].includes(s.page)?'shop':null;const box=document.getElementById('concept-compare');if(!box)return;box.hidden=!key;if(key){document.getElementById('concept-image').src='references/'+key+'.png';document.getElementById('concept-note').textContent=key==='warehouse'?'保留四列、品质角标、选中物品区；按最新要求移除分类和关闭按钮。':key==='pass'?'复用证件插画，状态与广告按钮为真实控件。旧图的体验、交易手续费和勘探权益不在本轮范围；未擅自恢复。':'柜台插画与三页签复用。取消协会建设、合作玩法；保留金币贡献兑换。';}},
 screen(c){const {s,engine,img,btn,num,esc}=c;const {ITEMS,GOODS}=MoleReview;
 if(s.page==='home'){const overdue=s.notes.find(n=>n.status==='runaway'),mature=s.notes.find(n=>n.status==='matured'),active=s.notes.find(n=>n.status==='active');const status=s.debt>0?`<h3>剩余债务</h3><b class="home-amount">${num(s.debt)}</b><p>还清债务后<br>即可开启放贷</p>${btn('前往还款','home.debt.open')}`:overdue?`<h3 class="bad">借款人跑路</h3><p>${overdue.name}</p><p>本金损失</p><b class="home-amount">${num(overdue.principal)}</b>${btn('了解','home.loan.runaway')}`:mature?`<h3>放贷时间已到</h3><p>${mature.name}</p><div class="home-loan-line">本金 <b>+${num(mature.principal)}</b></div><div class="home-loan-line">利息 <b>+${num(mature.interest)}</b></div><p>合计回款</p><b class="home-amount">${num(mature.principal+mature.interest)}</b>${btn('领取本息','home.loan.matured')}`:active?`<h3>放贷进行中</h3><p>${active.name}</p><p>剩余 ${Math.max(0,active.due-s.clock)} 小时</p>${btn('查看借据','home.loan.active')}`:`<h3>放贷业务</h3><p>VIP证${engine.pass()?'有效':'已过期'}</p>${btn('进入放贷','home.lending.open')}`;return `<div class="home-portrait">${img('mole_explorer','','avatars')}</div><section class="home-note">${status}</section><div class="hero">${img('mole_explorer','','avatars')}</div><div class="entry-grid">${[['trophy','排行榜','home.ranking.open'],['amethyst','交易所 · 未开放','home.locked_feature'],['warehouse','仓库图鉴','home.warehouse.open'],['vip_badge-v2','VIP证 · '+(engine.pass()?'有效':'过期'),'home.miner_pass'],['guild_shield','矿工协会','home.guild.open']].map(([i,t,a])=>btn(img(i)+t,a,'','secondary')).join('')}</div><button class="home-wealth" data-action="home.wealth.open"><strong>财富等级</strong>${img('trophy','')}<b>Lv.${s.wealth}</b><span>净财富</span><output>${num(s.coins-s.debt)}</output><span>最大深度</span><b>${num(s.depth)}米</b></button><button class="home-level" data-action="home.play"><b>第 ${s.level} 关</b><span>${s.n} × ${s.n}</span></button>${btn('继续挖矿','home.play','','home-start')}`;}
 const scene=`<div class="guild-scene" role="img" aria-label="鼹鼠柜台、矿灯与宝石箱"></div>`;
 const tabs=`<div class="guild-tabs">${[['aid','物资互助'],['mine','联合开采'],['shop','协会商店']].map(([id,t])=>btn(t,'guild.module.'+id,'',s.page===id?'selected':'secondary')).join('')}</div>`;
 const stats=`<div class="guild-stats"><span>${img('guild_shield')} Lv.3</span><button data-action="home.miner_pass" class="pass-state ${engine.pass()?'':'expired'}">VIP证 ${engine.pass()?Math.ceil((s.passUntil-s.clock)/24)+'天':'已过期'}</button><span>${img('coin')} ${num(s.contribution)}</span></div>`;
 if(s.page==='guild')return `${scene}<section class="guild-intro"><h3>${esc(s.guildName)} <small>Lv.3</small></h3><p>${esc(s.notice)}</p><div class="member-strip">${btn('成员名单 · '+s.members.length+'/30','guild.members.open','','secondary')}${s.president?btn('协会管理','guild.manage.open','','secondary'):''}</div></section>${stats}<div class="guild-modules">${[['ore_iron','物资互助','申请与捐赠','aid'],['treasure_chest','联合开采','自动开采矿石','mine'],['shop','协会商店','贡献兑换商品','shop']].map(([icon,t,sub,id])=>`<button data-action="guild.module.${id}" class="module-card"><b>${t}</b>${img(icon,'')}<span>${sub}</span></button>`).join('')}</div>`;
 if(s.page==='shop')return `${scene}${tabs}<section class="donation-banner">${img('coin','')}<div><b>金币贡献</b><small>100 金币 → 10 贡献</small></div>${btn('贡献金币','guild_shop.contribute.open','','small')}</section><div class="scroll shop-scroll"><div class="shop-products">${GOODS.map((g,i)=>`<article class="shop-product"><h3>${g[1]}</h3><div class="goods-middle">${img(g[0],'')}<div><b>${g[2]} 贡献</b><small>剩余 ${s.stock[i]}/${g[3]}</small></div></div>${btn(s.stock[i]?'兑换':'已售罄','guild_shop.item.select',i,'',!s.stock[i])}</article>`).join('')}</div></div>`;
 if(s.page==='aid')return `${scene}${stats}${tabs}<section class="aid-order"><h3>我的物资申请</h3><div class="aid-content">${img('ore_iron','')}<div><b>铁矿石 × 5</b><progress max="5" value="${s.aidReady?5:0}"></progress><small>${s.aidReady?'已送达':s.aidPosted?'等待捐赠':'尚未申请'}</small></div></div>${btn(s.aidReady?'领取物资':s.aidPosted?'等待成员捐赠':'申请物资',s.aidReady?'extra.aid.collect':'extra.aid.request','','',s.aidPosted&&!s.aidReady)}</section><section class="aid-order"><h3>岩仔的申请</h3><div class="aid-content">${img('ore_iron','')}<div><b>铁矿石 × 5</b><small>捐赠获得 20 贡献</small></div></div>${btn(s.aidDonated?'已捐赠':'捐赠 5 个','extra.aid.donate','','',s.aidDonated)}</section>`;
 if(s.page==='warehouse'){const selected=ITEMS[s.selectedItem],collected=s.inventory.filter((n,i)=>i!==6&&n>0).length,total=ITEMS.length-1,progress=Math.round(collected/total*100);return `<div class="collection-bar"><div class="collection-track" role="progressbar" aria-label="矿石收集进度" aria-valuemin="0" aria-valuemax="${total}" aria-valuenow="${collected}"><div class="collection-gauge"><span style="width:${progress}%"></span></div><strong>收集：${collected}/${total}</strong></div></div><div class="scroll" id="inventory-scroll"><div class="item-grid">${ITEMS.map((it,i)=>i===6?'':`<button class="item-card ${s.selectedItem===i?'selected-item ':''}${s.inventory[i]?'':'unowned'}" data-quality="${it[2]}" data-action="warehouse.item.${s.inventory[i]?'owned':'unowned'}" data-payload="${i}" aria-label="${it[1]}，${s.inventory[i]?'已拥有':'未发现，'+it[4]+'米出现'}">${it[0]?img(it[0],''):'<span class="undiscovered-gem" aria-label="未发现矿物轮廓"></span>'}<span class="item-depth">${it[4]}米出现</span></button>`).join('')}</div></div><section class="warehouse-dock"><button type="button" class="warehouse-detail-close" data-action="nav.back" aria-label="关闭仓库图鉴"></button><div class="selected-preview ${s.inventory[s.selectedItem]>0?'':'is-unowned'}">${selected[0]?img(selected[0],''):'<span class="undiscovered-gem"></span>'}<div><h3>${selected[1]} <small>${selected[2]}</small></h3><p>拥有数量：${num(s.inventory[s.selectedItem])}</p><span class="discovery-condition">${selected[4]}米出现</span></div></div><div class="discovery-note">深入对应矿层寻找</div></section>`;}
 if(s.page==='mine')return `${stats}${tabs}<section class="mine-illustration" role="img" aria-label="联合矿井自动运输矿石"></section><section class="aid-order"><h3>联合矿井 · Lv.3</h3><p class="good">${s.mineDue<=s.clock?'本轮开采完成':'剩余 '+(s.mineDue-s.clock)+' 小时'}</p><progress max="100" value="${Math.min(100,Math.max(0,100-(s.mineDue-s.clock)/6*100))}"></progress><div class="mine-yield">${[['ore_iron','铁矿石',12],['ore_copper','铜矿石',5],['ore_silver','银矿石',3]].map(([icon,t,n])=>`<div>${img(icon,'')}<b>${t}</b><span>× ${n}</span></div>`).join('')}</div></section><div class="grow"></div>${btn('领取矿石','guild.mine.collect')}`;
 if(s.page==='apply')return `${scene}<div class="application-condition"><b>入会申请条件</b><span class="${engine.pass()?'good':'bad'}">VIP证 · ${engine.pass()?'有效':'已过期'}</span><span>挖掘深度 ${s.depth} 米</span></div><div class="scroll stack">${[s.guildName,'深层勘探团'].map((n,i)=>`<button class="paper member" data-action="guild_apply.guild.select" data-payload="${i}">${img('guild_shield','avatar')}<div><strong>${esc(n)}</strong><p class="sub">${i?'1,000':'100'} 米深度 · ${i?'28':'18'}/30 人</p></div></button>`).join('')}${s.application?`<section class="aid-order"><p class="good">申请审核中</p>${btn('撤回申请','guild_apply.cancel_application','','secondary')}</section>`:''}</div>${btn('创建协会','guild_apply.create.open')}`;
 },
 modal(c){const {s,engine,img,btn,chosen}=c;if(s.modal!=='pass')return;
 const valid=engine.pass();const id=chosen?.includes('lending.pass')?'lending.pass.activate_ad':chosen?.includes('guild_apply.pass')?'guild_apply.pass.activate_ad':'home.miner_pass.renew_ad';
 return `<div class="license-card"><div class="license-live"><strong>${s.passStamps>=7?'30 天VIP证':'矿工通行证'}</strong><span>鼹鼠矿工 · 你</span><b class="license-stamp ${valid?'':'expired'}">${valid?'有效':'已过期'}</b><small>${valid?'剩余 '+Math.ceil(s.passUntil-s.clock)+' 小时':'观看广告补领'}</small></div></div><section class="license-progress"><div><b>累计 ${s.passStamps||0}/7</b><small>每日最多计入 2 次</small></div><div class="stamp-track">${Array.from({length:7},(_,i)=>`<span class="${i<(s.passStamps||0)?'stamped':''}">${img('guild_shield','')}</span>`).join('')}</div><p>${s.passStamps>=7?'已升级 30 天VIP证':'集满 7 次，升级 30 天VIP证'}</p></section><h3 class="rights-title">持证权益</h3><div class="license-rights">${[['guild_shield','进入矿工协会','加入协会，享受矿工权益'],['ore_iron','物资互助','申请与捐赠矿石'],['treasure_chest','联合开采','定时领取矿石'],['shop','协会商店','贡献兑换商品'],['loan_contract','解锁放贷业务','还清债务后开启']].map(([icon,t,sub],i)=>{const enabled=valid&&(i!==4||s.debt===0);return `<div>${img(icon,'')}<section><b>${t}</b><small>${sub}</small></section><span class="${enabled?'good':'bad'}">${enabled?'已生效':valid?'待还清':'已暂停'}</span></div>`;}).join('')}</div><div class="actions">${btn('观看广告 · '+(valid?'续期':'补领')+((s.passStamps>=7||s.passStamps===6&&(s.passStampDay!==Math.floor(s.clock/24)||(s.passStampsToday||0)<2))?' 30 天':' 3 天'),id)}</div>`;
 }
};
