/* Locked to imagegen-leaderboard-depth-clean-source.png. Art is blank; controls and data remain live. */
(()=>{const prior=window.productionUI;window.productionUI={...prior,
 compare(s){if(s.page==='ranking'&&!s.modal){const box=document.getElementById('concept-compare');box.hidden=false;document.getElementById('concept-image').src='references/ranking-'+s.rank+'-locked.png';document.getElementById('concept-note').textContent='本页锁定对应页签原稿。文字、页签和列表是实时控件；右上角统一提供关闭按钮，返回主界面。';return;}prior.compare(s);},
 screen(c){if(c.s.page!=='ranking')return prior.screen(c);const {s,btn,img,num}=c;const depth=s.rank==='depth';
 const names=depth?['深岩王','黑钻镐','铁轨客','地底风','老钻头','蓝晶帽','矿洞眼','小岩层']:['黄金鼻','岩老板','铜牙','水晶胡子','老矿灯','铁帽叔','石屑仔','铲王'];
 const scores=depth?[9850,9620,9430,9210,8970,8760,8540,8310]:[8820650,7944120,7501880,6980430,6725900,6490210,6218760,5995440];
 const score=i=>num(scores[i]??Math.max(0,scores[7]-(i-7)*(depth?110:12000)))+(depth?'米':'');
 return `<div class="exact-rank-surface ${depth?'is-depth':'is-wealth'}"><div class="exact-tabs">${btn(img('trophy')+' 财富榜','ranking.tab.wealth','',depth?'secondary':'selected')}${btn('<img class="icon" src="assets/visual/rank-pickaxe.png" alt=""> 深度榜','ranking.tab.depth','',depth?'selected':'secondary')}</div><div class="exact-cream"></div>${s.emptyRank?'<div class="exact-empty">暂无排名</div>':`<div class="exact-podium"><div class="podium-art" data-asset="assets/visual/rank-podium-equal-gap-v5.png" role="img" aria-label="银色奖座、王冠钻石金色奖座、铜色奖座"><span class="podium-sprite silver"></span><span class="podium-sprite gold"></span><span class="podium-sprite bronze"></span></div><div class="podium-data">${[1,0,2].map((i,j)=>`<div class="podium-label label-${j}"><b class="podium-number">${i+1}</b><strong>${names[i]}</strong><output>${score(i)}</output></div>`).join('')}</div></div><div class="exact-list-head"><span>名次</span><span>矿工</span><span>${depth?'最深完成':'财富值'}</span></div><div class="scroll exact-rank-list">${Array.from({length:97},(_,j)=>{const i=j+3;return `<div class="exact-rank-row"><b>${i+1}</b><span>${names[i]||'矿工 '+(i+1)}</span><strong>${score(i)}</strong></div>`;}).join('')}</div>`}<div class="exact-self"><section><span>我的排名</span><b>${s.emptyRank?'10,000+':depth?'1,246':'278'}</b></section><strong>贫穷矿工</strong><section><span>${depth?'最深完成':'财富值'}</span><b>${depth?num(s.depth)+'米':num(s.coins-s.debt)}</b></section></div></div>`;
 }};})();
