(()=>{const prior=window.productionUI;
window.productionUI={...prior,modal(c){if(c.s.modal==='onlineConfirm'){const x=c.engine.onlineReward(c.s.onlineConfirmation?.minutes),base=ActivityRewards.online.find(y=>y.minutes===x?.minutes);if(!x||!base)return '';const bonus=Math.floor(base.coins*x.passMultiplier)-base.coins;return `<div class="online-confirm"><p>是否领取本次奖励？</p><strong>${c.img('coin')} ${c.num(x.coins)}</strong><div class="online-confirm-bonus">${c.engine.pass()?'持证已加成':'持VIP证可多领'} <b>+${c.num(bonus)} 金币</b></div><div class="online-confirm-actions"><button class="game-btn" data-action="nav.back">暂不领取</button><button class="game-btn" data-action="rewards.claim.online" data-payload="${x.minutes}">确认领取</button></div></div>`;}if(!['checkin','achievements'].includes(c.s.modal))return prior.modal(c);const {engine,s,img,num}=c,r=engine.rewardState(),tab=s.rewardTab,check=s.modal==='checkin';
const tabs=check?[]:ActivityRewards.categories.map(x=>[x.id,x.name]);
const button=(id,payload,label,disabled)=>`<button class="game-btn" data-action="${id}" data-payload="${payload}" ${disabled?'disabled':''}>${label}</button>`;
let body='';if(check){const today=r.signedDays.includes(engine.rewardDay()),position=(r.signedDays.length-(today?1:0))%7;body=`<div class="checkin-days">${ActivityRewards.daily.map((coins,i)=>`<button type="button" ${i===position?'data-action="rewards.claim.daily"':''} ${today||i!==position?'disabled':''} class="checkin-day ${i<position||i===position&&today?'is-claimed':i===position?'is-current':''}"><span>第 ${i+1} 天</span>${img('coin')}<b>${num(coins)}</b><small>${i<position||i===position&&today?'✓ 已领取':i===position?'点击领取':'待领取'}</small></button>`).join('')}</div>`;}
else{body=`<div class="activity-list">${engine.achievementRows().filter(x=>x.id===tab).map(x=>`<div class="activity-row ${x.claimed?'is-claimed':x.value>=x.target?'is-ready':''}"><img class="achievement-badge" src="assets/icons/trophy.png" alt=""><div><strong>${x.name} · ${x.target}${x.id==='wealth'?'级':x.id==='levels'?'关':'种'}</strong><progress max="${x.target}" value="${Math.min(x.value,x.target)}"></progress><small>${x.value} / ${x.target}</small><span>${img('coin')} ${num(x.coins)}</span></div>${button('rewards.claim.achievement',x.key,x.claimed?'✓ 已领取':x.value>=x.target?'领取':'未达成',x.claimed||x.value<x.target)}</div>`).join('')}</div>`;}
if(check)body+=`<section class="online-milestones"><div class="online-summary">今日在线 <b data-online-clock>${Math.floor(r.seconds/60)}分 ${Math.floor(r.seconds%60)}秒</b></div><div class="online-track"><div class="online-track-line"><i data-online-fill></i></div>${ActivityRewards.online.map(config=>{const x=engine.onlineReward(config.minutes);const claimed=r.onlineClaims.includes(x.minutes),ready=r.seconds>=x.minutes*60;return `<div class="online-node ${claimed?'is-claimed':ready?'is-ready':''}" data-online-node="${x.minutes}"><span>${x.minutes<60?x.minutes+'分钟':x.minutes/60+'小时'}</span><button type="button" data-action="rewards.online.open" data-payload="${x.minutes}" aria-label="${x.minutes}分钟在线奖励，${x.coins}金币" ${claimed||!ready?'disabled':''}>${img('coin')}<i class="online-check">✓</i></button><b data-online-coins>${num(x.coins)}</b><small class="online-multiplier" data-online-multiplier>${'VIPx'+x.passMultiplier}</small><small data-online-status>${claimed?'':ready?'领取':'未达成'}</small></div>`;}).join('')}</div></section>`;
return `<div class="activity-panel">${check?'':'<div class="activity-tabs">'}${tabs.map(([id,label])=>`<button data-action="rewards.tab" data-payload="${id}" class="${tab===id?'selected':''}">${label}</button>`).join('')}${check?'':'</div>'}${body}</div>`;
}};
let last=performance.now(),visible=!document.hidden,save=0;
function tick(){const now=performance.now(),delta=(now-last)/1000;last=now;const e=window.review;if(!e)return;if(visible&&delta<5)e.addOnlineTime(delta);visible=!document.hidden;save+=delta;if(save>=15){e.saveWardrobeProgress();save=0;}const r=e.rewardState();const times=ActivityRewards.online.map(x=>x.minutes*60);let fill=0;for(let i=0;i<times.length-1;i++)if(r.seconds>=times[i])fill=(i+Math.min(1,(r.seconds-times[i])/(times[i+1]-times[i])))/4*100;document.querySelectorAll('[data-online-fill]').forEach(el=>el.style.width=fill+'%');document.querySelectorAll('[data-online-clock]').forEach(el=>el.textContent=Math.floor(r.seconds/60)+'分 '+Math.floor(r.seconds%60)+'秒');document.querySelectorAll('[data-action="rewards.online.open"]').forEach(el=>{const m=Number(el.dataset.payload),claimed=r.onlineClaims.includes(m);el.disabled=claimed||r.seconds<m*60;const node=el.closest('.online-node');if(node){const reward=e.onlineReward(m);node.querySelector('[data-online-coins]').textContent=reward.coins.toLocaleString('en-US');node.querySelector('[data-online-multiplier]').textContent='VIPx'+reward.passMultiplier;el.setAttribute('aria-label',m+'分钟在线奖励，'+reward.coins+'金币');node.classList.toggle('is-claimed',claimed);node.classList.toggle('is-ready',!claimed&&r.seconds>=m*60);node.querySelector('[data-online-status]').textContent=claimed?'':r.seconds>=m*60?'领取':'未达成';}});}
setInterval(tick,1000);document.addEventListener('visibilitychange',()=>{tick();window.review?.saveWardrobeProgress();});window.addEventListener('pagehide',()=>{tick();window.review?.saveWardrobeProgress();});
})();
