// Generated by tools/qa/compile-shared-ui-browser.cjs; do not hand-edit.
(()=>{const exports={};const require=()=>({});
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SHARED_SKINS = void 0;
exports.themeRole = themeRole;
exports.themeSkin = themeSkin;
exports.lightInk = lightInk;
exports.themeTextColor = themeTextColor;
const PrototypeMarkup_1 = require("./PrototypeMarkup");
/** Semantic decoration only: no state, geometry, actions, icons or text baked here. */
exports.SHARED_SKINS = ['panel', 'card', 'title', 'button', 'secondary', 'paper'];
const cards = new Set(('item-card beauty-choice profile-avatar-choice wardrobe-item checkin-day reward-item activity-row exact-rank-row exact-self credit-offer credit-note shop-exact-product guild-browser-card paper detail-stat profile-stat vip-benefit drop-quality-row').split(' '));
const surfaces = new Set(('beauty-current beauty-detail wardrobe-preview workshop-detail warehouse-dock debt-milestones debt-near debt-final-goal debt-payment debt-dialog-hero debt-dialog-summary credit-loan-hero credit-selection dialog-info dialog-hero dialog-total dialog-field detail-group dialog-rule-list mission-progress profile-identity profile-achievements profile-progress online-milestones guild-growth-entry shop-exact-donation shop-exact-products exact-cream building-unlock-card president-identity president-review president-notice mine-exact-panel mine-exact-progress mine-exact-yield vip-composite vip-slide vip-hero vip-benefits-section vip-account-progress pass-bottom aid-concept-request').split(' '));
function themeRole(m, parent, root = false) {
    if (root)
        return 'panel';
    if (m.tag === '#text' || m.tag === 'img' || m.tag === 'svg')
        return null;
    const c = (m.attrs.class || '').split(/\s+/), has = (s) => c.includes(s);
    // Open illustration / list surfaces: keep the shared outer frame, avoid nested wood frames.
    if (['dialog-info', 'dialog-hero', 'credit-loan-hero', 'debt-dialog-hero', 'detail-group', 'dialog-rule-list', 'detail-stat', 'beauty-detail', 'wardrobe-preview', 'profile-identity', 'profile-achievements', 'president-identity', 'debt-milestones', 'debt-final-goal', 'exact-cream', 'exact-rank-row', 'mine-exact-panel', 'shop-exact-products', 'vip-composite', 'vip-slide', 'vip-benefits-section'].some(has))
        return null;
    if (has('pv-link'))
        return null;
    if (has('drop-quality-row') || has('paper'))
        return 'paper';
    if (has('pv-claim') && 'disabled' in m.attrs)
        return null;
    if (has('pv-primary') && 'disabled' in m.attrs)
        return 'paper';
    if (['beauty-choice', 'wardrobe-item', 'shop-exact-product', 'credit-offer', 'reward-item', 'profile-avatar-choice'].some(has))
        return 'paper';
    if (m.tag === 'h2' || has('page-title') || has('guild-module-title'))
        return 'title';
    if (has('ui-close'))
        return 'secondary';
    if (m.tag === 'output')
        return 'secondary';
    if (has('activity-row') || c.some(x => surfaces.has(x)) || ['exact-rank-row', 'exact-self', 'credit-note', 'detail-stat', 'profile-stat', 'vip-benefit', 'guild-browser-card'].some(has))
        return 'paper';
    if (m.tag === 'button' && /tabs|vip-pager/.test((parent === null || parent === void 0 ? void 0 : parent.attrs.class) || '') && !has('selected') && !has('is-selected'))
        return 'paper';
    if (m.tag === 'button' && m.attrs['data-action'] === 'rewards.claim.achievement' && 'disabled' in m.attrs)
        return 'paper';
    if (c.some(x => cards.has(x) || surfaces.has(x)))
        return 'card';
    if (m.tag === 'input' && m.attrs.type === 'checkbox')
        return 'secondary';
    if (['input', 'textarea', 'select'].includes(m.tag))
        return 'card';
    if (has('game-btn') || m.tag === 'button' && /tabs|vip-pager/.test((parent === null || parent === void 0 ? void 0 : parent.attrs.class) || '')) {
        if (has('secondary') && !has('selected') && !has('is-selected'))
            return 'secondary';
        if (/tabs|vip-pager/.test((parent === null || parent === void 0 ? void 0 : parent.attrs.class) || '') && !has('selected') && !has('is-selected'))
            return 'secondary';
        return 'button';
    }
    return null;
}
function themeSkin(tree, path) {
    const m = (0, PrototypeMarkup_1.markupAt)(tree, path);
    if (!m)
        return null;
    const role = themeRole(m, path.length ? (0, PrototypeMarkup_1.markupAt)(tree, path.slice(0, -1)) : undefined, !path.length);
    return role ? 'shared-ui-v1/' + role : null;
}
function lightInk(value) {
    const hex = value === null || value === void 0 ? void 0 : value.match(/^#([\da-f]{6})/i), rgb = value === null || value === void 0 ? void 0 : value.match(/^rgba?\(([^)]+)/);
    const a = hex ? [0, 2, 4].map(i => parseInt(hex[1].slice(i, i + 2), 16)) : rgb ? rgb[1].split(',').slice(0, 3).map(Number) : [];
    return a.length === 3 && a[0] * .299 + a[1] * .587 + a[2] * .114 > 175;
}
function themeTextColor(tree, path, originalColor = '') {
    for (let i = path.length - 1; i >= 0; i--) {
        const p = path.slice(0, i), m = (0, PrototypeMarkup_1.markupAt)(tree, p);
        if (!m)
            continue;
        if (/(^|\s)(quality|quality-chip|drop-quality-tag|vip-card-state)(\s|$)/.test(m.attrs.class || ''))
            return null;
        const role = themeRole(m, i ? (0, PrototypeMarkup_1.markupAt)(tree, p.slice(0, -1)) : undefined, !i);
        if (role === 'title')
            return '#68421F';
        if (role === 'secondary')
            return '#FFF2CF';
        if (role === 'button')
            return 'disabled' in m.attrs ? '#4D4942' : '#4A2C10';
        if ((role === 'card' || role === 'paper') && lightInk(originalColor))
            return '#54351D';
        if (role === 'paper' && m.tag === 'button')
            return '#705636';
        // Keep rarity colors, warning/success text and character art unchanged.
    }
    return null;
}

function annotate(){
 document.querySelectorAll('#phone .modal, #phone #game[data-page]:not([data-page="home"])').forEach(root=>{
  const visit=el=>{
   const m={tag:el.tagName.toLowerCase(),attrs:Object.fromEntries([...el.attributes].map(a=>[a.name,a.value])),children:[]};
   const p=el.parentElement,parent=p?{attrs:{class:p.className||''}}:undefined;
   const role=exports.themeRole(m,parent,el===root);
   if(role){if(el.dataset.uiSkin!==role)el.dataset.uiSkin=role;}else if(el.dataset.uiSkin)delete el.dataset.uiSkin;
  };
  visit(root);root.querySelectorAll('*').forEach(visit);
  root.querySelectorAll('*').forEach(el=>{
   if(!el.closest('[data-ui-skin="card"],[data-ui-skin="paper"]')||el.closest('.quality,.quality-chip,.drop-quality-tag,.vip-card-state,[data-ui-skin="secondary"],[data-ui-skin="title"]')){delete el.dataset.uiInk;return;}
   if([...el.childNodes].some(n=>n.nodeType===3&&n.textContent.trim())&&exports.lightInk(getComputedStyle(el).color))el.dataset.uiInk='dark';
  });
 });
}
let scheduled=false;
const observer=new MutationObserver(()=>{if(scheduled)return;scheduled=true;queueMicrotask(()=>{scheduled=false;annotate();});});
observer.observe(document.getElementById('phone'),{subtree:true,childList:true,attributes:true,attributeFilter:['class','disabled','data-page']});
window.SharedSystemTheme={...exports,annotate};annotate();

})();
